# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "favorites",
            "0004_alter_favorite_created_at_alter_favorite_target_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "收藏记录",
                "verbose_name_plural": "收藏记录",
            },
        ),
    ]
