# Generated by Django 5.2.14 on 2026-06-09 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('trigger_event', models.CharField(choices=[('real_name_verified', '实名认证通过')], default='real_name_verified', max_length=50)),
                ('inviter_reward_amount', models.BigIntegerField(default=0)),
                ('invitee_reward_amount', models.BigIntegerField(default=0)),
                ('requires_manual_review', models.BooleanField(default=True)),
                ('allow_link', models.BooleanField(default=True)),
                ('allow_code', models.BooleanField(default=True)),
                ('display_level', models.CharField(choices=[('masked_progress', '脱敏进度')], default='masked_progress', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inviter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('registered', '已注册'), ('pending_review', '待审核'), ('review_rejected', '审核驳回'), ('reward_issued', '已发奖')], default='registered', max_length=32)),
                ('invitee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_referral_record', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referral_records', to=settings.AUTH_USER_MODEL)),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='referrals.referrallink')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ReferralRewardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=20)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('referral_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='referrals.referralrecord')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
