# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="referrallink",
            name="code",
            field=models.CharField(max_length=32, unique=True, verbose_name="编码"),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="inviter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_link",
                to=settings.AUTH_USER_MODEL,
                verbose_name="邀请人",
            ),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="referralrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="referralrecord",
            name="invitee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_referral_record",
                to=settings.AUTH_USER_MODEL,
                verbose_name="受邀人",
            ),
        ),
        migrations.AlterField(
            model_name="referralrecord",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_referral_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="邀请人",
            ),
        ),
        migrations.AlterField(
            model_name="referralrecord",
            name="referral_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="referrals.referrallink",
                verbose_name="邀请链接",
            ),
        ),
        migrations.AlterField(
            model_name="referralrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "已注册"),
                    ("pending_review", "待审核"),
                    ("review_rejected", "审核驳回"),
                    ("reward_issued", "已发奖"),
                ],
                default="registered",
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="referralrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="referralrewardreview",
            name="action",
            field=models.CharField(max_length=20, verbose_name="操作"),
        ),
        migrations.AlterField(
            model_name="referralrewardreview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="referralrewardreview",
            name="referral_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="referrals.referralrecord",
                verbose_name="邀请记录",
            ),
        ),
        migrations.AlterField(
            model_name="referralrewardreview",
            name="remark",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="备注"
            ),
        ),
        migrations.AlterField(
            model_name="referralrewardreview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="referralrewardreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="referralruleconfig",
            name="allow_code",
            field=models.BooleanField(default=True, verbose_name="允许邀请码"),
        ),
        migrations.AlterField(
            model_name="referralruleconfig",
            name="allow_link",
            field=models.BooleanField(default=True, verbose_name="允许邀请链接"),
        ),
        migrations.AlterField(
            model_name="referralruleconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="referralruleconfig",
            name="display_level",
            field=models.CharField(
                choices=[("masked_progress", "脱敏进度")],
                default="masked_progress",
                max_length=32,
                verbose_name="展示级别",
            ),
        ),
        migrations.AlterField(
            model_name="referralruleconfig",
            name="invitee_reward_amount",
            field=models.BigIntegerField(default=0, verbose_name="受邀人奖励金额"),
        ),
        migrations.AlterField(
            model_name="referralruleconfig",
            name="inviter_reward_amount",
            field=models.BigIntegerField(default=0, verbose_name="邀请人奖励金额"),
        ),
        migrations.AlterField(
            model_name="referralruleconfig",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="规则名称"),
        ),
        migrations.AlterField(
            model_name="referralruleconfig",
            name="requires_manual_review",
            field=models.BooleanField(default=True, verbose_name="是否需要人工审核"),
        ),
        migrations.AlterField(
            model_name="referralruleconfig",
            name="trigger_event",
            field=models.CharField(
                choices=[("real_name_verified", "实名认证通过")],
                default="real_name_verified",
                max_length=50,
                verbose_name="触发事件",
            ),
        ),
        migrations.AlterField(
            model_name="referralruleconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
