# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0002_alter_referrallink_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referrallink",
            options={"verbose_name": "邀请链接", "verbose_name_plural": "邀请链接"},
        ),
        migrations.AlterModelOptions(
            name="referralrecord",
            options={
                "ordering": ("-created_at", "-pk"),
                "verbose_name": "邀请记录",
                "verbose_name_plural": "邀请记录",
            },
        ),
        migrations.AlterModelOptions(
            name="referralrewardreview",
            options={
                "ordering": ("-created_at", "-pk"),
                "verbose_name": "邀请奖励审核",
                "verbose_name_plural": "邀请奖励审核",
            },
        ),
        migrations.AlterModelOptions(
            name="referralruleconfig",
            options={
                "verbose_name": "邀请奖励规则",
                "verbose_name_plural": "邀请奖励规则",
            },
        ),
    ]
