# Generated by Django 5.2.14 on 2026-06-05 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number_masked',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name_masked',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name_status',
            field=models.CharField(choices=[('unverified', '未实名'), ('pending', '待校验'), ('verified', '已实名'), ('rejected', '已驳回'), ('manual_review', '人工复核'), ('revoked', '已撤销')], db_index=True, default='unverified', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RealNameVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unverified', '未实名'), ('pending', '待校验'), ('verified', '已实名'), ('rejected', '已驳回'), ('manual_review', '人工复核'), ('revoked', '已撤销')], db_index=True, default='pending', max_length=32)),
                ('source', models.CharField(choices=[('user_submit', '用户主动提交'), ('business_gate', '业务拦截触发')], default='user_submit', max_length=32)),
                ('provider', models.CharField(choices=[('mock_auto', '模拟自动校验'), ('manual_admin', '后台人工处理')], default='mock_auto', max_length=32)),
                ('real_name_encrypted', models.TextField()),
                ('id_number_encrypted', models.TextField()),
                ('real_name_masked', models.CharField(max_length=64)),
                ('id_number_masked', models.CharField(max_length=32)),
                ('id_number_last4', models.CharField(blank=True, db_index=True, default='', max_length=4)),
                ('id_number_hash', models.CharField(db_index=True, max_length=64)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('review_note', models.TextField(blank=True, default='')),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=128)),
                ('provider_result', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_real_name_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_name_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RealNameVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', '提交认证'), ('auto_verified', '自动通过'), ('auto_rejected', '自动驳回'), ('moved_to_manual_review', '转人工复核'), ('manual_approved', '人工通过'), ('manual_rejected', '人工驳回'), ('revoked', '撤销实名')], max_length=32)),
                ('from_status', models.CharField(blank=True, choices=[('unverified', '未实名'), ('pending', '待校验'), ('verified', '已实名'), ('rejected', '已驳回'), ('manual_review', '人工复核'), ('revoked', '已撤销')], default='', max_length=32)),
                ('to_status', models.CharField(blank=True, choices=[('unverified', '未实名'), ('pending', '待校验'), ('verified', '已实名'), ('rejected', '已驳回'), ('manual_review', '人工复核'), ('revoked', '已撤销')], default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_name_log_entries', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.realnameverification')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
