# Generated by Codex on 2026-06-13

from django.db import migrations, models
from django.db.models import Q


def split_phone(phone):
    if not phone:
        return "", ""
    value = str(phone).strip().replace(" ", "")
    if not value:
        return "", ""
    if value.startswith("+") and "-" in value:
        country_code, national_number = value.split("-", 1)
        return country_code, national_number.replace("-", "")

    compact = value.replace("-", "")
    if compact.startswith("+86") and len(compact) > 3:
        return "+86", compact[3:]
    if compact.startswith("86") and len(compact) > 2:
        return "+86", compact[2:]
    if compact.startswith("1") and len(compact) == 11:
        return "+86", compact
    return "", compact


def backfill_phone_parts(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.exclude(phone__isnull=True).exclude(phone="").iterator():
        country_code, national_number = split_phone(user.phone)
        User.objects.filter(pk=user.pk).update(
            phone_country_code=country_code,
            phone_national_number=national_number,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_id_number_masked_user_real_name_masked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_country_code",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_national_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.RunPython(backfill_phone_parts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=~Q(phone_national_number=""),
                fields=("phone_country_code", "phone_national_number"),
                name="accounts_user_phone_parts_unique",
            ),
        ),
    ]
