# Generated by Codex on 2026-06-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_phone_split_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
