# Generated by Django 5.2.14 on 2026-06-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_realnameverification_id_card_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realnameverification',
            name='id_number_last4',
        ),
    ]
