# Generated by Django 5.2.14 on 2026-06-20 17:59

from django.db import migrations

import apps.media.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_realnameverification_id_number_last4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realnameverification',
            name='id_card_media',
            field=apps.media.fields.MediaRefsField(
                allowed_media_types=['image'],
                allowed_resource_types=['real_name_id_card'],
                blank=True,
                business_validators=['apps.accounts.services.validate_id_card_media_owner'],
                default=list,
                max_items=2,
                min_items=2,
                verbose_name='身份证图片',
            ),
        ),
    ]
