# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realnameverification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="failure_reason",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="失败原因"
            ),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="id_number_encrypted",
            field=models.TextField(verbose_name="身份证号密文"),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="id_number_hash",
            field=models.CharField(
                db_index=True, max_length=64, verbose_name="身份证号哈希"
            ),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="id_number_masked",
            field=models.CharField(max_length=32, verbose_name="脱敏身份证号"),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="is_current",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="是否当前记录"
            ),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="provider",
            field=models.CharField(
                choices=[
                    ("mock_auto", "模拟自动校验"),
                    ("manual_admin", "后台人工处理"),
                ],
                default="mock_auto",
                max_length=32,
                verbose_name="服务提供方",
            ),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="provider_request_id",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="服务方请求标识"
            ),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="provider_result",
            field=models.JSONField(blank=True, default=dict, verbose_name="服务方结果"),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="real_name_encrypted",
            field=models.TextField(verbose_name="实名姓名密文"),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="real_name_masked",
            field=models.CharField(max_length=64, verbose_name="脱敏实名姓名"),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="review_note",
            field=models.TextField(blank=True, default="", verbose_name="审核备注"),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_real_name_verifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="source",
            field=models.CharField(
                choices=[
                    ("user_submit", "用户主动提交"),
                    ("business_gate", "业务拦截触发"),
                ],
                default="user_submit",
                max_length=32,
                verbose_name="来源",
            ),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("unverified", "未实名"),
                    ("pending", "待校验"),
                    ("verified", "已实名"),
                    ("rejected", "已驳回"),
                    ("manual_review", "人工复核"),
                    ("revoked", "已撤销"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="realnameverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="real_name_verifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="realnameverificationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("submitted", "提交认证"),
                    ("auto_verified", "自动通过"),
                    ("auto_rejected", "自动驳回"),
                    ("moved_to_manual_review", "转人工复核"),
                    ("manual_approved", "人工通过"),
                    ("manual_rejected", "人工驳回"),
                    ("revoked", "撤销实名"),
                ],
                max_length=32,
                verbose_name="操作",
            ),
        ),
        migrations.AlterField(
            model_name="realnameverificationlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="realnameverificationlog",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unverified", "未实名"),
                    ("pending", "待校验"),
                    ("verified", "已实名"),
                    ("rejected", "已驳回"),
                    ("manual_review", "人工复核"),
                    ("revoked", "已撤销"),
                ],
                default="",
                max_length=32,
                verbose_name="原状态",
            ),
        ),
        migrations.AlterField(
            model_name="realnameverificationlog",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="realnameverificationlog",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="real_name_log_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AlterField(
            model_name="realnameverificationlog",
            name="to_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unverified", "未实名"),
                    ("pending", "待校验"),
                    ("verified", "已实名"),
                    ("rejected", "已驳回"),
                    ("manual_review", "人工复核"),
                    ("revoked", "已撤销"),
                ],
                default="",
                max_length=32,
                verbose_name="新状态",
            ),
        ),
        migrations.AlterField(
            model_name="realnameverificationlog",
            name="verification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="accounts.realnameverification",
                verbose_name="实名认证记录",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_number_masked",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="脱敏身份证号"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_country_code",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="手机号国家代码"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_national_number",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="手机号本地号码"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(default=False, verbose_name="手机号是否已验证"),
        ),
        migrations.AlterField(
            model_name="user",
            name="real_name_masked",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="脱敏实名姓名"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="real_name_status",
            field=models.CharField(
                choices=[
                    ("unverified", "未实名"),
                    ("pending", "待校验"),
                    ("verified", "已实名"),
                    ("rejected", "已驳回"),
                    ("manual_review", "人工复核"),
                    ("revoked", "已撤销"),
                ],
                db_index=True,
                default="unverified",
                max_length=32,
                verbose_name="实名认证状态",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="real_name_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="实名认证时间"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                default="Asia/Shanghai", max_length=63, verbose_name="时区"
            ),
        ),
    ]
