# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_realnameverification_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realnameverification",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "实名认证记录",
                "verbose_name_plural": "实名认证记录",
            },
        ),
        migrations.AlterModelOptions(
            name="realnameverificationlog",
            options={
                "ordering": ["created_at", "id"],
                "verbose_name": "实名认证操作日志",
                "verbose_name_plural": "实名认证操作日志",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
    ]
