# Generated by Django 5.2.14 on 2026-07-19 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0008_organization_description_organization_logo"),
        ("teams", "0003_team_address_team_business_hours_team_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamAnnouncement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, default="", max_length=150)),
                ("updated_by", models.CharField(blank=True, default="", max_length=150)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("status", models.CharField(choices=[("draft", "草稿"), ("published", "已发布"), ("withdrawn", "已撤回")], default="draft", max_length=20)),
                ("require_acknowledgement", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="team_announcements", to="organizations.organization")),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="published_team_announcements", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="announcements", to="teams.team")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AnnouncementReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="announcement_receipts", to=settings.AUTH_USER_MODEL)),
                ("announcement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="receipts", to="team_operations.teamannouncement")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WorkTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, default="", max_length=150)),
                ("updated_by", models.CharField(blank=True, default="", max_length=150)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("task_type", models.CharField(default="general", max_length=64)),
                ("priority", models.CharField(choices=[("normal", "普通"), ("high", "重要"), ("urgent", "紧急")], default="normal", max_length=20)),
                ("status", models.CharField(choices=[("active", "进行中"), ("completed", "已完成"), ("cancelled", "已取消")], default="active", max_length=20)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("url", models.CharField(blank=True, default="", max_length=500)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("creator", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_work_tasks", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="work_tasks", to="organizations.organization")),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="work_tasks", to="teams.team")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待接受"), ("in_progress", "进行中"), ("completed", "已完成"), ("rejected", "已拒绝"), ("cancelled", "已取消")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.TextField(blank=True)),
                ("assignee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_assignments", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="team_operations.worktask")),
            ],
            options={
                "ordering": ("task__due_at", "-created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="teamannouncement",
            index=models.Index(fields=["organization", "status", "-created_at"], name="team_ann_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="teamannouncement",
            index=models.Index(fields=["team", "status", "-created_at"], name="team_ann_team_status_idx"),
        ),
        migrations.AddIndex(
            model_name="announcementreceipt",
            index=models.Index(fields=["recipient", "acknowledged_at", "-created_at"], name="team_ann_recipient_idx"),
        ),
        migrations.AddConstraint(
            model_name="announcementreceipt",
            constraint=models.UniqueConstraint(fields=("announcement", "recipient"), name="team_ann_receipt_unique"),
        ),
        migrations.AddIndex(
            model_name="worktask",
            index=models.Index(fields=["organization", "status", "due_at"], name="work_task_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="worktask",
            index=models.Index(fields=["team", "status", "due_at"], name="work_task_team_status_idx"),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(fields=["assignee", "status", "-created_at"], name="task_assignment_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="taskassignment",
            constraint=models.UniqueConstraint(fields=("task", "assignee"), name="work_task_assignee_unique"),
        ),
    ]
