# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_alter_organization_archived_at_and_more"),
        ("team_operations", "0001_initial"),
        ("teams", "0005_alter_team_address_alter_team_business_hours_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcementreceipt",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="确认时间"),
        ),
        migrations.AlterField(
            model_name="announcementreceipt",
            name="announcement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="team_operations.teamannouncement",
                verbose_name="公告",
            ),
        ),
        migrations.AlterField(
            model_name="announcementreceipt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="announcementreceipt",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcement_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收人",
            ),
        ),
        migrations.AlterField(
            model_name="announcementreceipt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="接受时间"),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="执行人",
            ),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="拒绝时间"),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="result",
            field=models.TextField(blank=True, verbose_name="处理结果"),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待接受"),
                    ("in_progress", "进行中"),
                    ("completed", "已完成"),
                    ("rejected", "已拒绝"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="team_operations.worktask",
                verbose_name="任务",
            ),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="body",
            field=models.TextField(verbose_name="正文"),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_announcements",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_team_announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布人",
            ),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="require_acknowledgement",
            field=models.BooleanField(default=False, verbose_name="是否要求确认"),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("published", "已发布"),
                    ("withdrawn", "已撤回"),
                ],
                default="draft",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements",
                to="teams.team",
                verbose_name="团队",
            ),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="title",
            field=models.CharField(max_length=255, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="teamannouncement",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="取消时间"),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_work_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="data",
            field=models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="截止时间"),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_tasks",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="priority",
            field=models.CharField(
                choices=[("normal", "普通"), ("high", "重要"), ("urgent", "紧急")],
                default="normal",
                max_length=20,
                verbose_name="优先级",
            ),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "进行中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="active",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="task_type",
            field=models.CharField(
                default="general", max_length=64, verbose_name="任务类型"
            ),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_tasks",
                to="teams.team",
                verbose_name="团队",
            ),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="title",
            field=models.CharField(max_length=255, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="url",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="链接地址"
            ),
        ),
    ]
