# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team_operations", "0002_alter_announcementreceipt_acknowledged_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcementreceipt",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "公告接收记录",
                "verbose_name_plural": "公告接收记录",
            },
        ),
        migrations.AlterModelOptions(
            name="taskassignment",
            options={
                "ordering": ("task__due_at", "-created_at"),
                "verbose_name": "任务分配",
                "verbose_name_plural": "任务分配",
            },
        ),
        migrations.AlterModelOptions(
            name="teamannouncement",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "团队公告",
                "verbose_name_plural": "团队公告",
            },
        ),
        migrations.AlterModelOptions(
            name="worktask",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "工作任务",
                "verbose_name_plural": "工作任务",
            },
        ),
    ]
