# Generated by Django 5.2.14 on 2026-06-21 05:27

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.media.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0006_organization_lifecycle_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("roles", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="house_contacts", to="organizations.organization")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="house_contacts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Estate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=150)),
                ("developer", models.CharField(blank=True, max_length=150, null=True)),
                ("built_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "property_type",
                    models.CharField(choices=[("residential", "住宅"), ("commercial", "商业"), ("industrial", "工业"), ("mixed", "综合")], default="residential", max_length=32),
                ),
                ("province", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=64)),
                ("district", models.CharField(max_length=64)),
                ("address", models.CharField(max_length=255)),
                ("lat", models.DecimalField(blank=True, decimal_places=6, help_text="项目/小区级展示点定位", max_digits=10, null=True)),
                ("lng", models.DecimalField(blank=True, decimal_places=6, help_text="项目/小区级展示点定位", max_digits=10, null=True)),
                (
                    "images",
                    apps.media.fields.MediaRefsField(
                        allowed_media_types=["image"],
                        allowed_resource_types=["estate_image"],
                        blank=True,
                        business_validators=["apps.house.services.validate_org_scoped_media_refs"],
                        default=list,
                        max_items=9,
                        verbose_name="项目图片",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="estates", to="organizations.organization")),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("floors", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("under_floors", models.PositiveIntegerField(blank=True, null=True)),
                ("year_built", models.PositiveIntegerField(blank=True, null=True)),
                ("elevator", models.BooleanField(default=False)),
                ("lat", models.DecimalField(blank=True, decimal_places=6, help_text="楼栋级精确导航定位", max_digits=10, null=True)),
                ("lng", models.DecimalField(blank=True, decimal_places=6, help_text="楼栋级精确导航定位", max_digits=10, null=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="buildings", to="organizations.organization")),
                ("estate", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="buildings", to="house.estate")),
            ],
            options={
                "ordering": ["estate__name", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("room_number", models.CharField(max_length=64)),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("area", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("interior_area", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("bedrooms", models.PositiveIntegerField(blank=True, null=True)),
                ("living_rooms", models.PositiveIntegerField(blank=True, null=True)),
                ("bathrooms", models.PositiveIntegerField(blank=True, null=True)),
                ("kitchens", models.PositiveIntegerField(blank=True, null=True)),
                ("balconies", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "orientation",
                    models.CharField(
                        blank=True,
                        choices=[("south", "南"), ("north", "北"), ("east", "东"), ("west", "西"), ("south_north", "南北"), ("east_west", "东西")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("decoration", models.CharField(blank=True, choices=[("raw", "毛坯"), ("simple", "简装"), ("fine", "精装"), ("luxury", "豪装")], max_length=32, null=True)),
                ("has_elevator_access", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("vacant", "空置"), ("rented", "已租"), ("renovating", "装修中"), ("locked", "封存")], db_index=True, default="vacant", max_length=32
                    ),
                ),
                (
                    "images",
                    apps.media.fields.MediaRefsField(
                        allowed_media_types=["image"],
                        allowed_resource_types=["house_image"],
                        blank=True,
                        business_validators=["apps.house.services.validate_org_scoped_media_refs"],
                        default=list,
                        max_items=9,
                        verbose_name="房源图片",
                    ),
                ),
                (
                    "videos",
                    apps.media.fields.MediaRefsField(
                        allowed_media_types=["video"],
                        allowed_resource_types=["house_video"],
                        blank=True,
                        business_validators=["apps.house.services.validate_org_scoped_media_refs"],
                        default=list,
                        max_items=3,
                        verbose_name="房源视频",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("public_description", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("building", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="houses", to="house.building")),
                ("landlord", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="landlord_houses", to="house.contact")),
            ],
            options={
                "ordering": ["building__estate__name", "building__name", "room_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sign_at", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("deposit", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                (
                    "payment_day",
                    models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待生效"), ("active", "生效中"), ("expired", "已到期"), ("terminated", "已终止")], db_index=True, default="pending", max_length=32
                    ),
                ),
                (
                    "contract_files",
                    apps.media.fields.MediaRefsField(
                        allowed_media_types=["file"],
                        allowed_resource_types=["lease_contract"],
                        blank=True,
                        business_validators=["apps.house.services.validate_org_scoped_media_refs"],
                        default=list,
                        max_items=1,
                        verbose_name="租约合同",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("house", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leases", to="house.house")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leases", to="organizations.organization")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tenant_leases", to="house.contact")),
            ],
            options={
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ViewingRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(max_length=32)),
                ("scheduled_at", models.DateTimeField()),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("scheduled", "已预约"), ("viewed", "已带看"), ("canceled", "已取消"), ("no_show", "爽约"), ("converted", "已成交")],
                        db_index=True,
                        default="scheduled",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_to",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_viewing_records", to=settings.AUTH_USER_MODEL),
                ),
                ("contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="viewing_records", to="house.contact")),
                ("house", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="viewing_records", to="house.house")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="viewing_records", to="organizations.organization")),
            ],
            options={
                "ordering": ["-scheduled_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(fields=("organization", "phone"), name="house_contact_org_phone_unique"),
        ),
        migrations.AddConstraint(
            model_name="estate",
            constraint=models.UniqueConstraint(fields=("organization", "name"), name="house_estate_org_name_unique"),
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(fields=("estate", "name"), name="house_building_estate_name_unique"),
        ),
        migrations.AddConstraint(
            model_name="house",
            constraint=models.UniqueConstraint(fields=("building", "room_number"), name="house_building_room_unique"),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "active")), fields=("house",), name="house_one_active_lease_unique"),
        ),
    ]
