# Generated by Django 5.2.14 on 2026-06-21 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='source_viewing_record',
            field=models.ForeignKey(
                blank=True,
                help_text='成交来源带看记录，可为空。',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='converted_leases',
                to='house.viewingrecord',
            ),
        ),
    ]
