# Generated by Django 5.2.14 on 2026-06-21 09:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_lease_source_viewing_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='asking_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='house',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='house',
            name='publish_status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('unpublished', '已下架')], db_index=True, default='draft', max_length=32),
        ),
    ]
