# Generated by Django 5.2.14 on 2026-07-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("house", "0008_building_images"),
        ("organizations", "0007_organizationinvite_access_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyResponsibility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_property_responsibilities", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="property_responsibilities", to="house.estate"),
                ),
                (
                    "landlord",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="property_responsibilities", to="house.contact"),
                ),
                (
                    "member",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="property_responsibilities", to="organizations.organizationmember"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="property_responsibilities", to="organizations.organization"),
                ),
            ],
            options={
                "ordering": ["member__user__username", "landlord__name", "estate__name", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("estate__isnull", True), ("landlord__isnull", False)) | models.Q(("estate__isnull", False), ("landlord__isnull", True)),
                        name="house_responsibility_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("landlord__isnull", False)),
                        fields=("member", "landlord"),
                        name="house_responsibility_member_landlord_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("estate__isnull", False)),
                        fields=("member", "estate"),
                        name="house_responsibility_member_estate_unique",
                    ),
                ],
            },
        ),
    ]
