# Generated by Django 5.2.14 on 2026-07-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("house", "0013_remove_estate_building_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("house", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorites", to="house.house")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="house_favorites", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "constraints": [models.UniqueConstraint(fields=("user", "house"), name="house_favorite_user_house_unique")],
            },
        ),
    ]
