# Generated by Django 5.2.14 on 2026-08-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("house", "0015_contact_public_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseMatchShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, default="", max_length=150)),
                ("updated_by", models.CharField(blank=True, default="", max_length=150)),
                ("share_key", models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ("title", models.CharField(max_length=150)),
                ("remark", models.TextField(blank=True, default="")),
                ("mode", models.CharField(choices=[("manual", "手工配房"), ("dynamic", "动态配房")], max_length=16)),
                ("house_ids", models.JSONField(blank=True, default=list)),
                ("criteria", models.JSONField(blank=True, default=dict)),
                ("criteria_version", models.PositiveSmallIntegerField(default=1)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="house_match_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="house_match_shares",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
