# Generated by Django 5.2.14 on 2026-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("house", "0016_housematchshare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="status",
            field=models.CharField(
                choices=[
                    ("vacant", "空置"),
                    ("listed", "招租"),
                    ("rented", "已租"),
                    ("renovating", "装修"),
                    ("inactive", "已停用"),
                ],
                db_index=True,
                default="vacant",
                max_length=32,
            ),
        ),
    ]
