# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocation", "0001_initial"),
        ("house", "0017_alter_house_status"),
        ("organizations", "0012_alter_organization_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="地址"),
        ),
        migrations.AlterField(
            model_name="building",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="building",
            name="elevator",
            field=models.BooleanField(default=False, verbose_name="是否有电梯"),
        ),
        migrations.AlterField(
            model_name="building",
            name="estate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buildings",
                to="house.estate",
                verbose_name="项目小区",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="floors",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="地上楼层数",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="楼栋级精确导航定位",
                max_digits=10,
                null=True,
                verbose_name="纬度",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="楼栋级精确导航定位",
                max_digits=10,
                null=True,
                verbose_name="经度",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(max_length=100, verbose_name="楼栋名称"),
        ),
        migrations.AlterField(
            model_name="building",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buildings",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="标签"),
        ),
        migrations.AlterField(
            model_name="building",
            name="under_floors",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="地下楼层数"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="building",
            name="year_built",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="建成年份"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, verbose_name="联系人姓名"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="house_contacts",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=32, verbose_name="手机号"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="public_key",
            field=models.UUIDField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="公开标识",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="roles",
            field=models.JSONField(blank=True, default=list, verbose_name="角色列表"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="house_contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="地址"
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="built_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="建成年份"
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="city",
            field=models.CharField(max_length=64, verbose_name="城市"),
        ),
        migrations.AlterField(
            model_name="estate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="estate",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="estate",
            name="developer",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="开发商"
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="display_name",
            field=models.CharField(max_length=150, verbose_name="显示名称"),
        ),
        migrations.AlterField(
            model_name="estate",
            name="district",
            field=models.CharField(max_length=64, verbose_name="区县"),
        ),
        migrations.AlterField(
            model_name="estate",
            name="lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="项目/小区级展示点定位",
                max_digits=10,
                null=True,
                verbose_name="纬度",
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="项目/小区级展示点定位",
                max_digits=10,
                null=True,
                verbose_name="经度",
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="name",
            field=models.CharField(max_length=100, verbose_name="项目名称"),
        ),
        migrations.AlterField(
            model_name="estate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estates",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("residential", "住宅"),
                    ("commercial", "商业"),
                    ("industrial", "工业"),
                    ("mixed", "综合"),
                ],
                default="residential",
                max_length=32,
                verbose_name="物业类型",
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="province",
            field=models.CharField(max_length=64, verbose_name="省份"),
        ),
        migrations.AlterField(
            model_name="estate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="house",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="建筑面积",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="asking_rent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="挂牌租金",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="balconies",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="阳台数"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="bathrooms",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="卫生间数"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="bedrooms",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="卧室数"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="houses",
                to="house.building",
                verbose_name="楼栋",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="house",
            name="decoration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("raw", "毛坯"),
                    ("simple", "简装"),
                    ("fine", "精装"),
                    ("luxury", "豪装"),
                ],
                max_length=32,
                null=True,
                verbose_name="装修情况",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="deposit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="押金金额",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="extra",
            field=models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
        ),
        migrations.AlterField(
            model_name="house",
            name="floor",
            field=models.IntegerField(blank=True, null=True, verbose_name="楼层"),
        ),
        migrations.AlterField(
            model_name="house",
            name="has_elevator_access",
            field=models.BooleanField(default=False, verbose_name="是否可使用电梯"),
        ),
        migrations.AlterField(
            model_name="house",
            name="interior_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="套内面积",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="internal_notes",
            field=models.TextField(blank=True, verbose_name="内部备注"),
        ),
        migrations.AlterField(
            model_name="house",
            name="kitchens",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="厨房数"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="landlord",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="landlord_houses",
                to="house.contact",
                verbose_name="房东",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="living_rooms",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="客厅数"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("south", "南"),
                    ("north", "北"),
                    ("east", "东"),
                    ("west", "西"),
                    ("south_north", "南北"),
                    ("east_west", "东西"),
                ],
                max_length=32,
                null=True,
                verbose_name="朝向",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="public_description",
            field=models.TextField(blank=True, verbose_name="公开描述"),
        ),
        migrations.AlterField(
            model_name="house",
            name="room_number",
            field=models.CharField(max_length=64, verbose_name="房号"),
        ),
        migrations.AlterField(
            model_name="house",
            name="status",
            field=models.CharField(
                choices=[
                    ("vacant", "空置"),
                    ("listed", "招租"),
                    ("rented", "已租"),
                    ("renovating", "装修"),
                    ("inactive", "已停用"),
                ],
                db_index=True,
                default="vacant",
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="标签"),
        ),
        migrations.AlterField(
            model_name="house",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="housefavorite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="housefavorite",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="house.house",
                verbose_name="房源",
            ),
        ),
        migrations.AlterField(
            model_name="housefavorite",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="housefavorite",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="housefavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="consultant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="house_match_shares",
                to=settings.AUTH_USER_MODEL,
                verbose_name="顾问",
            ),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="criteria",
            field=models.JSONField(blank=True, default=dict, verbose_name="筛选条件"),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="criteria_version",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="条件版本"),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="过期时间"
            ),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="house_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="房源标识列表"
            ),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="mode",
            field=models.CharField(
                choices=[("manual", "手工配房"), ("dynamic", "动态配房")],
                max_length=16,
                verbose_name="模式",
            ),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="house_match_shares",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="remark",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="share_key",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="分享标识",
            ),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="title",
            field=models.CharField(max_length=150, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="housematchshare",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="押金",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="end_date",
            field=models.DateField(verbose_name="结束日期"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="extra",
            field=models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="house.house",
                verbose_name="房源",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="monthly_rent",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="月租金",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="payment_day",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="每月付款日",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="sign_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="签约时间"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="source_viewing_record",
            field=models.ForeignKey(
                blank=True,
                help_text="成交来源带看记录，可为空。",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="converted_leases",
                to="house.viewingrecord",
                verbose_name="来源带看记录",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="start_date",
            field=models.DateField(verbose_name="开始日期"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待生效"),
                    ("active", "生效中"),
                    ("expired", "已到期"),
                    ("terminated", "已终止"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_leases",
                to="house.contact",
                verbose_name="租客",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="propertyresponsibility",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_responsibilities",
                to="house.building",
                verbose_name="楼栋",
            ),
        ),
        migrations.AlterField(
            model_name="propertyresponsibility",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="propertyresponsibility",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="propertyresponsibility",
            name="estate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_responsibilities",
                to="house.estate",
                verbose_name="项目小区",
            ),
        ),
        migrations.AlterField(
            model_name="propertyresponsibility",
            name="landlord",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_responsibilities",
                to="house.contact",
                verbose_name="房东",
            ),
        ),
        migrations.AlterField(
            model_name="propertyresponsibility",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_responsibilities",
                to="organizations.organizationmember",
                verbose_name="组织成员",
            ),
        ),
        migrations.AlterField(
            model_name="propertyresponsibility",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_responsibilities",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="propertyresponsibility",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="propertyresponsibility",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_viewing_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="负责人",
            ),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="viewing_records",
                to="house.contact",
                verbose_name="联系人",
            ),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="customer_name",
            field=models.CharField(max_length=100, verbose_name="客户姓名"),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="customer_phone",
            field=models.CharField(max_length=32, verbose_name="客户手机号"),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="extra",
            field=models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="viewing_records",
                to="house.house",
                verbose_name="房源",
            ),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="viewing_records",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="scheduled_at",
            field=models.DateTimeField(verbose_name="预约时间"),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "已预约"),
                    ("viewed", "已带看"),
                    ("canceled", "已取消"),
                    ("no_show", "爽约"),
                    ("converted", "已成交"),
                ],
                db_index=True,
                default="scheduled",
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="viewingrecord",
            name="viewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="实际带看时间"
            ),
        ),
        migrations.CreateModel(
            name="LeaseAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "allocation_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lease_allocation",
                        to="allocation.allocationrequest",
                        verbose_name="分配申请",
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation",
                        to="house.lease",
                        verbose_name="租约",
                    ),
                ),
            ],
            options={
                "verbose_name": "租约分配关联",
                "verbose_name_plural": "租约分配关联",
                "ordering": ("-created_at", "-pk"),
            },
        ),
    ]
