# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0018_alter_building_address_alter_building_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={
                "ordering": ["estate__name", "name", "id"],
                "verbose_name": "楼栋",
                "verbose_name_plural": "楼栋",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["name", "id"],
                "verbose_name": "联系人",
                "verbose_name_plural": "联系人",
            },
        ),
        migrations.AlterModelOptions(
            name="estate",
            options={
                "ordering": ["name", "id"],
                "verbose_name": "项目小区",
                "verbose_name_plural": "项目小区",
            },
        ),
        migrations.AlterModelOptions(
            name="house",
            options={
                "ordering": [
                    "building__estate__name",
                    "building__name",
                    "room_number",
                    "id",
                ],
                "verbose_name": "房源",
                "verbose_name_plural": "房源",
            },
        ),
        migrations.AlterModelOptions(
            name="housefavorite",
            options={
                "ordering": ["-updated_at", "-id"],
                "verbose_name": "房源收藏",
                "verbose_name_plural": "房源收藏",
            },
        ),
        migrations.AlterModelOptions(
            name="housematchshare",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "房源匹配分享",
                "verbose_name_plural": "房源匹配分享",
            },
        ),
        migrations.AlterModelOptions(
            name="lease",
            options={
                "ordering": ["-start_date", "-id"],
                "verbose_name": "租约",
                "verbose_name_plural": "租约",
            },
        ),
        migrations.AlterModelOptions(
            name="propertyresponsibility",
            options={
                "ordering": [
                    "member__user__username",
                    "landlord__name",
                    "building__name",
                    "estate__name",
                    "id",
                ],
                "verbose_name": "房源责任分配",
                "verbose_name_plural": "房源责任分配",
            },
        ),
        migrations.AlterModelOptions(
            name="viewingrecord",
            options={
                "ordering": ["-scheduled_at", "-id"],
                "verbose_name": "带看记录",
                "verbose_name_plural": "带看记录",
            },
        ),
    ]
