# Generated by Django 5.2 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("house", "0019_alter_building_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contact",
            name="house_contact_org_phone_unique",
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("organization", "name", "phone"),
                name="house_contact_org_name_phone_unique",
            ),
        ),
    ]
