# Generated by Django 5.2 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("house", "0020_contact_name_phone_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="housematchshare",
            name="last_accessed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后访问时间"),
        ),
        migrations.AddField(
            model_name="housematchshare",
            name="revoked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="失效时间"),
        ),
        migrations.AddField(
            model_name="housematchshare",
            name="view_count",
            field=models.PositiveBigIntegerField(default=0, verbose_name="访问次数"),
        ),
    ]
