# Generated by Django 5.2.14 on 2026-07-24 16:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_initial_catalog(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    PlanEntitlement = apps.get_model("subscriptions", "PlanEntitlement")
    PlanPrice = apps.get_model("subscriptions", "PlanPrice")
    SubscriptionSettings = apps.get_model("subscriptions", "SubscriptionSettings")
    plans = (
        ("free", "免费版", 10, 3, 1, 50, 0, 0, {}),
        ("standard", "标准版", 20, 10, 3, 500, 9900, 99900, {"data_export": True}),
        ("professional", "专业版", 30, 30, 10, 3000, 29900, 299900, {"data_export": True, "business_analytics": True, "batch_operations": True}),
        (
            "enterprise",
            "企业版",
            40,
            100,
            30,
            20000,
            69900,
            699900,
            {"data_export": True, "business_analytics": True, "batch_operations": True, "advanced_access_control": True, "api_integration": True},
        ),
    )
    for code, name, display_order, member_limit, team_limit, house_limit, month_amount, year_amount, feature_flags in plans:
        plan, _ = Plan.objects.get_or_create(code=code, defaults={"name": name, "display_order": display_order, "is_active": True})
        PlanEntitlement.objects.get_or_create(
            plan=plan,
            version=1,
            defaults={
                "member_limit": member_limit,
                "team_limit": team_limit,
                "house_limit": house_limit,
                "feature_flags": feature_flags,
                "is_current": True,
            },
        )
        for billing_cycle, amount in (("month", month_amount), ("year", year_amount)):
            PlanPrice.objects.get_or_create(plan=plan, billing_cycle=billing_cycle, version=1, defaults={"amount": amount, "is_current": True})
    SubscriptionSettings.objects.get_or_create(singleton=True, defaults={"organization_creation_limit": 3})


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0009_alter_organization_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, default="", max_length=150)),
                ("updated_by", models.CharField(blank=True, default="", max_length=150)),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "subscriptions_plan",
                "ordering": ("display_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="SubscriptionSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("singleton", models.BooleanField(default=True, editable=False, unique=True)),
                ("organization_creation_limit", models.PositiveIntegerField(default=3)),
            ],
            options={
                "verbose_name": "订阅全局设置",
                "verbose_name_plural": "订阅全局设置",
                "db_table": "subscriptions_settings",
            },
        ),
        migrations.CreateModel(
            name="OrganizationInvoiceProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_type", models.CharField(choices=[("personal", "个人"), ("company", "企业")], default="company", max_length=16)),
                ("title", models.CharField(max_length=128)),
                ("tax_number", models.CharField(blank=True, default="", max_length=64)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("registered_address", models.CharField(blank=True, default="", max_length=255)),
                ("registered_phone", models.CharField(blank=True, default="", max_length=32)),
                ("bank_name", models.CharField(blank=True, default="", max_length=128)),
                ("bank_account", models.CharField(blank=True, default="", max_length=128)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="invoice_profile", to="organizations.organization")),
            ],
            options={
                "db_table": "subscriptions_organization_invoice_profile",
            },
        ),
        migrations.CreateModel(
            name="SaaSOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_no", models.CharField(db_index=True, max_length=40, unique=True)),
                ("order_type", models.CharField(choices=[("initial_purchase", "首次购买"), ("renewal", "续费"), ("upgrade", "套餐升级")], max_length=24)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending_payment", "待支付"), ("paid", "已支付"), ("closed", "已关闭"), ("payment_failed", "支付失败")],
                        db_index=True,
                        default="pending_payment",
                        max_length=24,
                    ),
                ),
                (
                    "close_reason",
                    models.CharField(blank=True, choices=[("timeout", "支付超时"), ("superseded", "已被新订单替代"), ("provider_failed", "渠道失败")], default="", max_length=24),
                ),
                ("billing_cycle", models.CharField(choices=[("month", "月付"), ("year", "年付")], max_length=16)),
                ("plan_snapshot", models.JSONField(default=dict)),
                ("price_snapshot", models.JSONField(default=dict)),
                ("entitlement_snapshot", models.JSONField(default=dict)),
                ("list_amount", models.PositiveIntegerField()),
                ("credit_amount", models.PositiveIntegerField(default=0)),
                ("payable_amount", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("refund_status", models.CharField(choices=[("none", "未退款"), ("partial", "部分退款"), ("full", "全额退款")], default="none", max_length=16)),
                ("refunded_amount", models.PositiveIntegerField(default=0)),
                ("refund_reason", models.TextField(blank=True, default="")),
                ("refund_proof", models.CharField(blank=True, default="", max_length=500)),
                ("refund_subscription_action", models.CharField(blank=True, choices=[("keep", "保留订阅"), ("end", "立即结束订阅")], default="", max_length=16)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_saas_orders", to=settings.AUTH_USER_MODEL),
                ),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="saas_orders", to="organizations.organization")),
                (
                    "refunded_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="refunded_saas_orders", to=settings.AUTH_USER_MODEL),
                ),
                ("target_plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="subscriptions.plan")),
            ],
            options={
                "db_table": "subscriptions_saas_order",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(choices=[("wechat", "微信支付")], default="wechat", max_length=16)),
                ("payment_mode", models.CharField(choices=[("native", "微信扫码支付"), ("miniprogram", "微信小程序支付")], max_length=16)),
                ("transaction_no", models.CharField(max_length=40, unique=True)),
                ("provider_trade_no", models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待支付"), ("succeeded", "支付成功"), ("failed", "支付失败"), ("exception", "异常待处理")], default="pending", max_length=16
                    ),
                ),
                ("callback_event_id", models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("request_snapshot", models.JSONField(blank=True, default=dict)),
                ("response_snapshot", models.JSONField(blank=True, default=dict)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="subscriptions.saasorder")),
            ],
            options={
                "db_table": "subscriptions_payment_transaction",
            },
        ),
        migrations.CreateModel(
            name="InvoiceRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("profile_snapshot", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("processing", "处理中"), ("issued", "已开票"), ("rejected", "已拒绝"), ("cancelled", "已取消")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, default="", max_length=128)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("file_url", models.URLField(blank=True, default="")),
                ("admin_note", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_invoice_requests", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "processed_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processed_invoice_requests", to=settings.AUTH_USER_MODEL),
                ),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="invoice_request", to="subscriptions.saasorder")),
            ],
            options={
                "db_table": "subscriptions_invoice_request",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("trial", "试用"), ("paid", "付费")], max_length=16)),
                ("status", models.CharField(choices=[("trialing", "试用中"), ("active", "已生效"), ("ended", "已结束")], max_length=16)),
                ("billing_cycle", models.CharField(blank=True, choices=[("month", "月付"), ("year", "年付")], default="", max_length=16)),
                ("plan_snapshot", models.JSONField(default=dict)),
                ("price_snapshot", models.JSONField(default=dict)),
                ("entitlement_snapshot", models.JSONField(default=dict)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("trial_started_at", models.DateTimeField(blank=True, null=True)),
                ("trial_ended_at", models.DateTimeField(blank=True, null=True)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="subscription", to="organizations.organization")),
                (
                    "source_order",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activated_subscriptions", to="subscriptions.saasorder"),
                ),
                (
                    "trial_granted_to",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="granted_subscription_trials", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "subscriptions_subscription",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.PositiveBigIntegerField()),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscription_audit_logs", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "organization",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="subscription_audit_logs", to="organizations.organization"),
                ),
            ],
            options={
                "db_table": "subscriptions_audit_log",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="PlanEntitlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("member_limit", models.PositiveIntegerField(blank=True, help_text="null 表示不限", null=True)),
                ("team_limit", models.PositiveIntegerField(blank=True, help_text="null 表示不限", null=True)),
                ("house_limit", models.PositiveIntegerField(blank=True, help_text="null 表示不限", null=True)),
                ("house_counting_rule", models.CharField(default="all", max_length=64)),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
                ("is_current", models.BooleanField(default=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entitlements", to="subscriptions.plan")),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "subscriptions_plan_entitlement",
                "ordering": ("plan", "-version"),
                "constraints": [
                    models.UniqueConstraint(fields=("plan", "version"), name="subscriptions_entitlement_plan_version_unique"),
                    models.UniqueConstraint(condition=models.Q(("is_current", True)), fields=("plan",), name="subscriptions_one_current_entitlement"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("billing_cycle", models.CharField(choices=[("month", "月付"), ("year", "年付")], max_length=16)),
                ("version", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("amount", models.PositiveIntegerField(help_text="含税价格，单位：分")),
                ("is_current", models.BooleanField(default=True)),
                ("display_note", models.CharField(blank=True, default="", max_length=255)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="prices", to="subscriptions.plan")),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "subscriptions_plan_price",
                "ordering": ("plan", "billing_cycle", "-version"),
                "constraints": [
                    models.UniqueConstraint(fields=("plan", "billing_cycle", "version"), name="subscriptions_price_plan_cycle_version_unique"),
                    models.UniqueConstraint(condition=models.Q(("is_current", True)), fields=("plan", "billing_cycle"), name="subscriptions_one_current_price_per_cycle"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="saasorder",
            index=models.Index(fields=["organization", "status"], name="sub_order_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["order", "status"], name="sub_payment_order_status_idx"),
        ),
        migrations.RunPython(seed_initial_catalog, migrations.RunPython.noop),
    ]
