# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_alter_organization_archived_at_and_more"),
        ("subscriptions", "0002_move_payment_transaction_to_payments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicerequest",
            name="admin_note",
            field=models.TextField(blank=True, default="", verbose_name="管理员备注"),
        ),
        migrations.AlterField(
            model_name="invoicerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="invoicerequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invoice_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="invoicerequest",
            name="file_url",
            field=models.URLField(blank=True, default="", verbose_name="文件地址"),
        ),
        migrations.AlterField(
            model_name="invoicerequest",
            name="invoice_number",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="发票号码"
            ),
        ),
        migrations.AlterField(
            model_name="invoicerequest",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开票时间"),
        ),
        migrations.AlterField(
            model_name="invoicerequest",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_request",
                to="subscriptions.saasorder",
                verbose_name="订单",
            ),
        ),
        migrations.AlterField(
            model_name="invoicerequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_invoice_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
        migrations.AlterField(
            model_name="invoicerequest",
            name="profile_snapshot",
            field=models.JSONField(default=dict, verbose_name="开票资料快照"),
        ),
        migrations.AlterField(
            model_name="invoicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("processing", "处理中"),
                    ("issued", "已开票"),
                    ("rejected", "已拒绝"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=16,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="invoicerequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="organizationinvoiceprofile",
            name="bank_account",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="银行账号"
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvoiceprofile",
            name="bank_name",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="开户银行"
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvoiceprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="organizationinvoiceprofile",
            name="invoice_type",
            field=models.CharField(
                choices=[("personal", "个人"), ("company", "企业")],
                default="company",
                max_length=16,
                verbose_name="发票类型",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvoiceprofile",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_profile",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvoiceprofile",
            name="recipient_email",
            field=models.EmailField(max_length=254, verbose_name="收件邮箱"),
        ),
        migrations.AlterField(
            model_name="organizationinvoiceprofile",
            name="registered_address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="注册地址"
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvoiceprofile",
            name="registered_phone",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="注册电话"
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvoiceprofile",
            name="tax_number",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="纳税人识别号"
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvoiceprofile",
            name="title",
            field=models.CharField(max_length=128, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="organizationinvoiceprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="code",
            field=models.SlugField(max_length=32, unique=True, verbose_name="编码"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="display_order",
            field=models.PositiveIntegerField(default=0, verbose_name="显示顺序"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=64, verbose_name="套餐名称"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="planentitlement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="planentitlement",
            name="feature_flags",
            field=models.JSONField(blank=True, default=dict, verbose_name="功能开关"),
        ),
        migrations.AlterField(
            model_name="planentitlement",
            name="house_counting_rule",
            field=models.CharField(
                default="all", max_length=64, verbose_name="房源计数规则"
            ),
        ),
        migrations.AlterField(
            model_name="planentitlement",
            name="house_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="null 表示不限",
                null=True,
                verbose_name="房源数量上限",
            ),
        ),
        migrations.AlterField(
            model_name="planentitlement",
            name="is_current",
            field=models.BooleanField(default=True, verbose_name="是否当前记录"),
        ),
        migrations.AlterField(
            model_name="planentitlement",
            name="member_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="null 表示不限",
                null=True,
                verbose_name="成员数量上限",
            ),
        ),
        migrations.AlterField(
            model_name="planentitlement",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entitlements",
                to="subscriptions.plan",
                verbose_name="套餐",
            ),
        ),
        migrations.AlterField(
            model_name="planentitlement",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布人",
            ),
        ),
        migrations.AlterField(
            model_name="planentitlement",
            name="team_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="null 表示不限",
                null=True,
                verbose_name="团队数量上限",
            ),
        ),
        migrations.AlterField(
            model_name="planentitlement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="planentitlement",
            name="version",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="版本",
            ),
        ),
        migrations.AlterField(
            model_name="planprice",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="含税价格，单位：分", verbose_name="金额"
            ),
        ),
        migrations.AlterField(
            model_name="planprice",
            name="billing_cycle",
            field=models.CharField(
                choices=[("month", "月付"), ("year", "年付")],
                max_length=16,
                verbose_name="计费周期",
            ),
        ),
        migrations.AlterField(
            model_name="planprice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="planprice",
            name="display_note",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="展示说明"
            ),
        ),
        migrations.AlterField(
            model_name="planprice",
            name="is_current",
            field=models.BooleanField(default=True, verbose_name="是否当前记录"),
        ),
        migrations.AlterField(
            model_name="planprice",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prices",
                to="subscriptions.plan",
                verbose_name="套餐",
            ),
        ),
        migrations.AlterField(
            model_name="planprice",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布人",
            ),
        ),
        migrations.AlterField(
            model_name="planprice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="planprice",
            name="version",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="版本",
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="billing_cycle",
            field=models.CharField(
                choices=[("month", "月付"), ("year", "年付")],
                max_length=16,
                verbose_name="计费周期",
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="close_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("timeout", "支付超时"),
                    ("superseded", "已被新订单替代"),
                    ("provider_failed", "渠道失败"),
                ],
                default="",
                max_length=24,
                verbose_name="关闭原因",
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="关闭时间"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_saas_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="credit_amount",
            field=models.PositiveIntegerField(default=0, verbose_name="抵扣金额"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="entitlement_snapshot",
            field=models.JSONField(default=dict, verbose_name="权益快照"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="expires_at",
            field=models.DateTimeField(db_index=True, verbose_name="过期时间"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="list_amount",
            field=models.PositiveIntegerField(verbose_name="原价金额"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="order_no",
            field=models.CharField(
                db_index=True, max_length=40, unique=True, verbose_name="订单号"
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("initial_purchase", "首次购买"),
                    ("renewal", "续费"),
                    ("upgrade", "套餐升级"),
                ],
                max_length=24,
                verbose_name="订单类型",
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="saas_orders",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="payable_amount",
            field=models.PositiveIntegerField(verbose_name="应付金额"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="plan_snapshot",
            field=models.JSONField(default=dict, verbose_name="套餐快照"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="price_snapshot",
            field=models.JSONField(default=dict, verbose_name="价格快照"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="refund_proof",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="退款凭证"
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="refund_reason",
            field=models.TextField(blank=True, default="", verbose_name="退款原因"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("none", "未退款"),
                    ("partial", "部分退款"),
                    ("full", "全额退款"),
                ],
                default="none",
                max_length=16,
                verbose_name="退款状态",
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="refund_subscription_action",
            field=models.CharField(
                blank=True,
                choices=[("keep", "保留订阅"), ("end", "立即结束订阅")],
                default="",
                max_length=16,
                verbose_name="退款后的订阅处理",
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="refunded_amount",
            field=models.PositiveIntegerField(default=0, verbose_name="退款金额"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="退款时间"),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="refunded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunded_saas_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="退款操作人",
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "待支付"),
                    ("paid", "已支付"),
                    ("closed", "已关闭"),
                    ("payment_failed", "支付失败"),
                ],
                db_index=True,
                default="pending_payment",
                max_length=24,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="target_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="subscriptions.plan",
                verbose_name="目标套餐",
            ),
        ),
        migrations.AlterField(
            model_name="saasorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="billing_cycle",
            field=models.CharField(
                blank=True,
                choices=[("month", "月付"), ("year", "年付")],
                default="",
                max_length=16,
                verbose_name="计费周期",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="到期时间"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="entitlement_snapshot",
            field=models.JSONField(default=dict, verbose_name="权益快照"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="kind",
            field=models.CharField(
                choices=[("trial", "试用"), ("paid", "付费")],
                max_length=16,
                verbose_name="类型",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan_snapshot",
            field=models.JSONField(default=dict, verbose_name="套餐快照"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="price_snapshot",
            field=models.JSONField(default=dict, verbose_name="价格快照"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="source_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activated_subscriptions",
                to="subscriptions.saasorder",
                verbose_name="来源订单",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trialing", "试用中"),
                    ("active", "已生效"),
                    ("ended", "已结束"),
                ],
                max_length=16,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="trial_ended_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="试用结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="trial_granted_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_subscription_trials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="试用权益授予用户",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="trial_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="试用开始时间"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="subscriptionauditlog",
            name="action",
            field=models.CharField(max_length=64, verbose_name="操作"),
        ),
        migrations.AlterField(
            model_name="subscriptionauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionauditlog",
            name="after",
            field=models.JSONField(blank=True, default=dict, verbose_name="变更后数据"),
        ),
        migrations.AlterField(
            model_name="subscriptionauditlog",
            name="before",
            field=models.JSONField(blank=True, default=dict, verbose_name="变更前数据"),
        ),
        migrations.AlterField(
            model_name="subscriptionauditlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="subscriptionauditlog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription_audit_logs",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionauditlog",
            name="target_id",
            field=models.PositiveBigIntegerField(verbose_name="目标标识"),
        ),
        migrations.AlterField(
            model_name="subscriptionauditlog",
            name="target_type",
            field=models.CharField(max_length=64, verbose_name="目标类型"),
        ),
        migrations.AlterField(
            model_name="subscriptionauditlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="subscriptionsettings",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="subscriptionsettings",
            name="organization_creation_limit",
            field=models.PositiveIntegerField(
                default=3, verbose_name="可创建组织数量上限"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionsettings",
            name="singleton",
            field=models.BooleanField(
                default=True, editable=False, unique=True, verbose_name="单例标记"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionsettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
