# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_invoicerequest_admin_note_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoicerequest",
            options={
                "ordering": ("-created_at", "-pk"),
                "verbose_name": "开票申请",
                "verbose_name_plural": "开票申请",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationinvoiceprofile",
            options={
                "verbose_name": "组织开票资料",
                "verbose_name_plural": "组织开票资料",
            },
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ("display_order", "pk"),
                "verbose_name": "套餐",
                "verbose_name_plural": "套餐",
            },
        ),
        migrations.AlterModelOptions(
            name="planentitlement",
            options={
                "ordering": ("plan", "-version"),
                "verbose_name": "套餐权益",
                "verbose_name_plural": "套餐权益",
            },
        ),
        migrations.AlterModelOptions(
            name="planprice",
            options={
                "ordering": ("plan", "billing_cycle", "-version"),
                "verbose_name": "套餐价格",
                "verbose_name_plural": "套餐价格",
            },
        ),
        migrations.AlterModelOptions(
            name="saasorder",
            options={
                "ordering": ("-created_at", "-pk"),
                "verbose_name": "SaaS 订单",
                "verbose_name_plural": "SaaS 订单",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "组织订阅", "verbose_name_plural": "组织订阅"},
        ),
        migrations.AlterModelOptions(
            name="subscriptionauditlog",
            options={
                "ordering": ("-created_at", "-pk"),
                "verbose_name": "订阅审计日志",
                "verbose_name_plural": "订阅审计日志",
            },
        ),
    ]
