# Generated by Django 5.2.14 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_alter_invoicerequest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saasorder",
            name="close_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("timeout", "支付超时"),
                    ("superseded", "已被新订单替代"),
                    ("provider_failed", "渠道失败"),
                    ("user_cancelled", "用户取消"),
                ],
                default="",
                max_length=24,
                verbose_name="关闭原因",
            ),
        ),
    ]
