# Generated by Django 5.2.14 on 2026-08-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_migrate_legacy_transactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="金额，单位：分", verbose_name="金额"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="biz_id",
            field=models.CharField(max_length=64, verbose_name="业务标识"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="biz_type",
            field=models.CharField(max_length=64, verbose_name="业务类型"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="callback_event_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                unique=True,
                verbose_name="回调事件标识",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="description",
            field=models.CharField(max_length=128, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="expires_at",
            field=models.DateTimeField(verbose_name="过期时间"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="payment_mode",
            field=models.CharField(
                choices=[("native", "微信扫码支付"), ("miniprogram", "微信小程序支付")],
                max_length=16,
                verbose_name="支付方式",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[("wechat", "微信支付")],
                default="wechat",
                max_length=16,
                verbose_name="服务提供方",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider_trade_no",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                unique=True,
                verbose_name="服务方交易号",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="request_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="请求快照"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="response_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="响应快照"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待支付"),
                    ("succeeded", "支付成功"),
                    ("failed", "支付失败"),
                    ("exception", "异常待处理"),
                ],
                default="pending",
                max_length=16,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="transaction_no",
            field=models.CharField(max_length=64, unique=True, verbose_name="交易号"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="金额，单位：分", verbose_name="金额"
            ),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="biz_id",
            field=models.CharField(max_length=64, verbose_name="业务标识"),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="biz_type",
            field=models.CharField(max_length=64, verbose_name="业务类型"),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="error_code",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="错误码"
            ),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="error_message",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="错误信息"
            ),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="executed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="执行时间"),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="idempotency_key",
            field=models.CharField(max_length=120, unique=True, verbose_name="幂等键"),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="out_trade_no",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="商户订单号"
            ),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="payee_snapshot",
            field=models.JSONField(default=dict, verbose_name="收款方快照"),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="provider",
            field=models.CharField(
                choices=[("wechat", "微信支付")],
                default="wechat",
                max_length=16,
                verbose_name="服务提供方",
            ),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="provider_trade_no",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="服务方交易号"
            ),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="request_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="请求快照"),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="response_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="响应快照"),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待发起"),
                    ("processing", "处理中"),
                    ("succeeded", "成功"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=16,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="payouttransaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
