# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_paymenttransaction_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={"verbose_name": "支付交易", "verbose_name_plural": "支付交易"},
        ),
        migrations.AlterModelOptions(
            name="payouttransaction",
            options={
                "ordering": ("-created_at", "-pk"),
                "verbose_name": "付款交易",
                "verbose_name_plural": "付款交易",
            },
        ),
    ]
