# Generated by Django 5.2.14 on 2026-05-16 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_add_is_primary_to_organizationmember'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('value_type', models.CharField(choices=[('text', '文本'), ('password', '密码'), ('json', 'JSON'), ('boolean', '布尔'), ('integer', '整数')], default='text', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_default',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_overrides', to='app_settings.defaultsetting')),
            ],
            options={
                'db_table': 'settings_organization',
                'unique_together': {('organization', 'setting')},
            },
        ),
        migrations.CreateModel(
            name='TeamSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField()),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_overrides', to='app_settings.defaultsetting')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='teams.team')),
            ],
            options={
                'db_table': 'settings_team',
                'unique_together': {('team', 'setting')},
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_user',
                'unique_together': {('user', 'key')},
            },
        ),
    ]
