# Generated by Django 5.2.14 on 2026-07-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0006_property_rental_default_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultsetting",
            name="widget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("input", "输入框"),
                    ("textarea", "多行文本"),
                    ("password", "密码框"),
                    ("switch", "开关"),
                    ("input_number", "数字输入框"),
                    ("select", "选择器"),
                    ("json_editor", "JSON 编辑器"),
                    ("location_picker", "地址选择器"),
                ],
                max_length=20,
            ),
        ),
    ]
