# Generated by Django 5.2.14 on 2026-08-27 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0009_property_rental_vacancy_sync"),
        ("organizations", "0011_alter_organizationmember_unique_together_and_more"),
        ("teams", "0004_alter_team_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationsetting",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="teamsetting",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="usersetting",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="organizationsetting",
            constraint=models.UniqueConstraint(fields=("organization", "setting"), name="settings_org_setting_unique"),
        ),
        migrations.AddConstraint(
            model_name="teamsetting",
            constraint=models.UniqueConstraint(fields=("team", "setting"), name="settings_team_setting_unique"),
        ),
        migrations.AddConstraint(
            model_name="usersetting",
            constraint=models.UniqueConstraint(fields=("user", "key"), name="settings_user_key_unique"),
        ),
    ]
