# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0010_alter_organizationsetting_unique_together_and_more"),
        ("organizations", "0012_alter_organization_archived_at_and_more"),
        ("teams", "0005_alter_team_address_alter_team_business_hours_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultsetting",
            name="category",
            field=models.CharField(blank=True, max_length=50, verbose_name="分类"),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="key",
            field=models.CharField(max_length=100, unique=True, verbose_name="设置键"),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="label",
            field=models.CharField(blank=True, max_length=100, verbose_name="显示名称"),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="ui",
            field=models.JSONField(blank=True, default=dict, verbose_name="界面配置"),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="value",
            field=models.JSONField(verbose_name="值"),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("text", "文本"),
                    ("password", "密码"),
                    ("json", "JSON"),
                    ("boolean", "布尔"),
                    ("integer", "整数"),
                    ("float", "浮点数"),
                ],
                default="text",
                max_length=20,
                verbose_name="值类型",
            ),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="widget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("input", "输入框"),
                    ("textarea", "多行文本"),
                    ("password", "密码框"),
                    ("switch", "开关"),
                    ("input_number", "数字输入框"),
                    ("select", "选择器"),
                    ("json_editor", "JSON 编辑器"),
                    ("location_picker", "地址选择器"),
                    ("tags", "标签输入"),
                ],
                max_length=20,
                verbose_name="控件类型",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsetting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="organizationsetting",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="organizationsetting",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsetting",
            name="setting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="org_overrides",
                to="app_settings.defaultsetting",
                verbose_name="设置项",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsetting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="organizationsetting",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="organizationsetting",
            name="value",
            field=models.JSONField(verbose_name="值"),
        ),
        migrations.AlterField(
            model_name="teamsetting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="teamsetting",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="teamsetting",
            name="setting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team_overrides",
                to="app_settings.defaultsetting",
                verbose_name="设置项",
            ),
        ),
        migrations.AlterField(
            model_name="teamsetting",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="teams.team",
                verbose_name="团队",
            ),
        ),
        migrations.AlterField(
            model_name="teamsetting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="teamsetting",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="teamsetting",
            name="value",
            field=models.JSONField(verbose_name="值"),
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="key",
            field=models.CharField(max_length=100, verbose_name="设置键"),
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="value",
            field=models.JSONField(verbose_name="值"),
        ),
    ]
