# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0011_alter_defaultsetting_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defaultsetting",
            options={
                "ordering": ["key"],
                "verbose_name": "默认设置",
                "verbose_name_plural": "默认设置",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationsetting",
            options={"verbose_name": "组织设置", "verbose_name_plural": "组织设置"},
        ),
        migrations.AlterModelOptions(
            name="teamsetting",
            options={"verbose_name": "团队设置", "verbose_name_plural": "团队设置"},
        ),
        migrations.AlterModelOptions(
            name="usersetting",
            options={"verbose_name": "用户设置", "verbose_name_plural": "用户设置"},
        ),
    ]
