# Generated by Django 5.2.14 on 2026-05-24 10:43

import apps.base.storage
import apps.media.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('avatar', '用户头像'), ('org_logo', '组织 Logo')], max_length=32)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(storage=apps.base.storage.S3MediaStorage(), upload_to=apps.media.models._media_upload_to)),
                ('file_size', models.PositiveIntegerField(help_text='bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
