# Generated by Codex on 2026-06-01

from django.db import migrations, models

import apps.media.models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(upload_to=apps.media.models._media_upload_to),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
