# Generated by Django 5.2.14 on 2026-08-29 02:51

import apps.media.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0008_alter_mediafile_resource_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(
                upload_to=apps.media.models._media_upload_to, verbose_name="文件"
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="file_size",
            field=models.PositiveIntegerField(
                help_text="bytes", verbose_name="文件大小"
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="original_filename",
            field=models.CharField(max_length=255, verbose_name="原始文件名"),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("avatar", "用户头像"),
                    ("org_logo", "组织 Logo"),
                    ("real_name_id_card", "实名认证身份证图片"),
                    ("estate_image", "项目图片"),
                    ("building_image", "楼栋图片"),
                    ("house_image", "房源图片"),
                    ("house_video", "房源视频"),
                    ("lease_contract", "租约合同"),
                ],
                max_length=32,
                verbose_name="资源类型",
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="thumbnail",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.media.models._media_upload_to,
                verbose_name="缩略图",
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="thumbnail_enqueued_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="缩略图入队时间"
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="thumbnail_generated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="缩略图生成时间"
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="thumbnail_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="缩略图开始处理时间"
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="thumbnail_status",
            field=models.CharField(
                choices=[
                    ("not_requested", "未请求"),
                    ("pending", "等待生成"),
                    ("processing", "生成中"),
                    ("ready", "已生成"),
                    ("failed", "生成失败"),
                ],
                default="not_requested",
                max_length=16,
                verbose_name="缩略图状态",
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="uploader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_files",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传人",
            ),
        ),
    ]
