# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0009_alter_mediafile_created_at_alter_mediafile_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediafile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "媒体文件",
                "verbose_name_plural": "媒体文件",
            },
        ),
    ]
