# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0012_alter_organization_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "不通过"),
                            ("expired", "已过期"),
                            ("voided", "已作废"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="申请状态",
                    ),
                ),
                (
                    "basis_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="计算基数",
                    ),
                ),
                (
                    "distribution_method",
                    models.CharField(
                        choices=[("percentage", "按比例"), ("fixed", "固定金额")],
                        max_length=20,
                        verbose_name="分配方式",
                    ),
                ),
                (
                    "distribution_rate_bp",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10000)],
                        verbose_name="分配比例（万分比）",
                    ),
                ),
                (
                    "fixed_distributable_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="固定可分配金额",
                    ),
                ),
                (
                    "distributable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="可分配金额",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=3, verbose_name="币种"),
                ),
                (
                    "source_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="业务来源快照"
                    ),
                ),
                (
                    "submitted_by_name_snapshot",
                    models.CharField(max_length=150, verbose_name="申请人姓名快照"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(db_index=True, verbose_name="提交时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="审核截止时间"),
                ),
                (
                    "reviewed_by_name_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="审核人姓名快照",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "review_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="审核不通过原因"
                    ),
                ),
                (
                    "voided_by_name_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="作废人姓名快照",
                    ),
                ),
                (
                    "voided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="作废时间"
                    ),
                ),
                (
                    "void_reason",
                    models.TextField(blank=True, default="", verbose_name="作废原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_requests",
                        to="organizations.organization",
                        verbose_name="所属组织",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_allocation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_allocation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voided_allocation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作废人",
                    ),
                ),
            ],
            options={
                "verbose_name": "分配申请",
                "verbose_name_plural": "分配申请",
                "ordering": ("-submitted_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="AllocationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="项目名称")),
                (
                    "effect",
                    models.CharField(
                        choices=[("increase", "增加"), ("decrease", "扣减")],
                        max_length=20,
                        verbose_name="增减方向",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="金额",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="备注"
                    ),
                ),
                (
                    "allocation_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="allocation.allocationrequest",
                        verbose_name="所属分配申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "分配计算项",
                "verbose_name_plural": "分配计算项",
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="AllocationShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beneficiary_name_snapshot",
                    models.CharField(max_length=150, verbose_name="受益人姓名快照"),
                ),
                (
                    "weight_bp",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="分配权重（万分比）",
                    ),
                ),
                (
                    "credited_basis_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="归属计算基数",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="分配金额",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="备注"
                    ),
                ),
                (
                    "allocation_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shares",
                        to="allocation.allocationrequest",
                        verbose_name="所属分配申请",
                    ),
                ),
                (
                    "beneficiary_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_shares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="受益人",
                    ),
                ),
            ],
            options={
                "verbose_name": "受益人分配份额",
                "verbose_name_plural": "受益人分配份额",
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="AccrualEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beneficiary_name_snapshot",
                    models.CharField(max_length=150, verbose_name="受益人姓名快照"),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("allocation", "业务分配"),
                            ("manual_increase", "人工增加"),
                            ("manual_decrease", "人工扣减"),
                            ("reversal", "冲销"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="流水类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="应计金额"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=3, verbose_name="币种"),
                ),
                (
                    "effective_at",
                    models.DateTimeField(db_index=True, verbose_name="生效时间"),
                ),
                (
                    "effective_month",
                    models.DateField(db_index=True, verbose_name="归属月份"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "beneficiary_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accrual_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="受益人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_accrual_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accrual_entries",
                        to="organizations.organization",
                        verbose_name="所属组织",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="allocation.accrualentry",
                        verbose_name="被冲销流水",
                    ),
                ),
                (
                    "allocation_share",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accrual_entry",
                        to="allocation.allocationshare",
                        verbose_name="来源分配份额",
                    ),
                ),
            ],
            options={
                "verbose_name": "应计收益流水",
                "verbose_name_plural": "应计收益流水",
                "ordering": ("-effective_at", "-pk"),
            },
        ),
        migrations.AddIndex(
            model_name="allocationrequest",
            index=models.Index(
                fields=["organization", "status", "expires_at"],
                name="alloc_req_status_exp_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("basis_amount__gte", 0)),
                name="allocation_request_basis_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("distributable_amount__gte", 0)),
                name="allocation_request_pool_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency", "CNY")),
                name="allocation_request_currency_cny",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("submitted_at"))),
                name="allocation_request_expiry_after_submit",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("distribution_method", "percentage"),
                        ("distribution_rate_bp__gte", 0),
                        ("distribution_rate_bp__isnull", False),
                        ("distribution_rate_bp__lte", 10000),
                        ("fixed_distributable_amount__isnull", True),
                    ),
                    models.Q(
                        ("distribution_method", "fixed"),
                        ("distribution_rate_bp__isnull", True),
                        ("fixed_distributable_amount__gte", 0),
                        ("fixed_distributable_amount__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="allocation_request_distribution_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("review_reason", ""),
                        ("reviewed_at__isnull", True),
                        ("reviewed_by__isnull", True),
                        ("reviewed_by_name_snapshot", ""),
                        ("status", "pending"),
                        ("void_reason", ""),
                        ("voided_at__isnull", True),
                        ("voided_by__isnull", True),
                        ("voided_by_name_snapshot", ""),
                    ),
                    models.Q(
                        ("review_reason", ""),
                        ("reviewed_at__isnull", False),
                        ("reviewed_by__isnull", False),
                        ("status", "approved"),
                        ("void_reason", ""),
                        ("voided_at__isnull", True),
                        ("voided_by__isnull", True),
                        ("voided_by_name_snapshot", ""),
                        models.Q(("reviewed_by_name_snapshot", ""), _negated=True),
                    ),
                    models.Q(
                        ("reviewed_at__isnull", False),
                        ("reviewed_by__isnull", False),
                        ("status", "rejected"),
                        ("void_reason", ""),
                        ("voided_at__isnull", True),
                        ("voided_by__isnull", True),
                        ("voided_by_name_snapshot", ""),
                        models.Q(("review_reason", ""), _negated=True),
                        models.Q(("reviewed_by_name_snapshot", ""), _negated=True),
                    ),
                    models.Q(
                        ("review_reason", ""),
                        ("reviewed_at__isnull", True),
                        ("reviewed_by__isnull", True),
                        ("reviewed_by_name_snapshot", ""),
                        ("status", "expired"),
                        ("void_reason", ""),
                        ("voided_at__isnull", True),
                        ("voided_by__isnull", True),
                        ("voided_by_name_snapshot", ""),
                    ),
                    models.Q(
                        ("review_reason", ""),
                        ("reviewed_at__isnull", False),
                        ("reviewed_by__isnull", False),
                        ("status", "voided"),
                        ("voided_at__isnull", False),
                        ("voided_by__isnull", False),
                        models.Q(("reviewed_by_name_snapshot", ""), _negated=True),
                        models.Q(("voided_by_name_snapshot", ""), _negated=True),
                        models.Q(("void_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="allocation_request_status_audit_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="allocation_item_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationshare",
            constraint=models.UniqueConstraint(
                fields=("allocation_request", "beneficiary_user"),
                name="allocation_request_beneficiary_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight_bp__gte", 1), ("weight_bp__lte", 10000)),
                name="allocation_share_weight_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("credited_basis_amount__gte", 0)),
                name="allocation_share_credit_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated_amount__gte", 0)),
                name="allocation_share_amount_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="accrualentry",
            index=models.Index(
                fields=["organization", "beneficiary_user", "effective_month"],
                name="accrual_org_user_month_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accrualentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="accrual_entry_amount_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="accrualentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency", "CNY")),
                name="accrual_entry_currency_cny",
            ),
        ),
        migrations.AddConstraint(
            model_name="accrualentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("allocation_share__isnull", False),
                        ("amount__gt", 0),
                        ("entry_type", "allocation"),
                        ("reversal_of__isnull", True),
                    ),
                    models.Q(
                        ("allocation_share__isnull", True),
                        ("amount__gt", 0),
                        ("entry_type", "manual_increase"),
                        ("reversal_of__isnull", True),
                        models.Q(("reason", ""), _negated=True),
                    ),
                    models.Q(
                        ("allocation_share__isnull", True),
                        ("amount__lt", 0),
                        ("entry_type", "manual_decrease"),
                        ("reversal_of__isnull", True),
                        models.Q(("reason", ""), _negated=True),
                    ),
                    models.Q(
                        ("allocation_share__isnull", True),
                        ("amount__lt", 0),
                        ("entry_type", "reversal"),
                        ("reversal_of__isnull", False),
                        models.Q(("reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="accrual_entry_source_sign_shape",
            ),
        ),
    ]
