# Generated by Django 5.2.14 on 2026-08-29 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_simplify_allocation_fields'),
        ('teams', '0006_alter_team_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrequest',
            name='rule_source',
            field=models.CharField(choices=[('default', '平台默认'), ('organization', '租户设置'), ('team', '团队设置')], default='default', max_length=20, verbose_name='规则来源'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_requests', to='teams.team', verbose_name='归属团队'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='team_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='归属团队名称快照'),
        ),
    ]
