# Generated by Django 5.2.14 on 2026-06-08 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("available_balance", models.BigIntegerField(default=0)),
                ("frozen_balance", models.BigIntegerField(default=0)),
                ("total_income", models.BigIntegerField(default=0)),
                ("total_withdrawn", models.BigIntegerField(default=0)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="wallet_account", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WalletLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_type", models.CharField(max_length=64)),
                ("amount_delta", models.BigIntegerField()),
                ("available_balance_after", models.BigIntegerField()),
                ("frozen_balance_after", models.BigIntegerField()),
                ("biz_type", models.CharField(blank=True, default="", max_length=100)),
                ("biz_id", models.CharField(blank=True, default="", max_length=100)),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                ("operator", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ledgers", to="wallet.walletaccount")),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.BigIntegerField()),
                ("fee_amount", models.BigIntegerField(default=0)),
                ("net_amount", models.BigIntegerField()),
                ("client_request_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "待审核"),
                            ("cancelled", "已撤销"),
                            ("rejected", "已驳回"),
                            ("approved", "已通过待打款"),
                            ("paying", "打款中"),
                            ("paid", "已打款"),
                            ("failed", "打款失败"),
                        ],
                        default="pending_review",
                        max_length=32,
                    ),
                ),
                ("pay_channel", models.CharField(max_length=32)),
                ("payee_account_snapshot", models.JSONField(default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "reviewed_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_withdrawals", to=settings.AUTH_USER_MODEL),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="withdrawal_requests", to=settings.AUTH_USER_MODEL)),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="withdrawal_requests", to="wallet.walletaccount")),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="WithdrawalPayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=50)),
                ("out_trade_no", models.CharField(max_length=64, unique=True)),
                ("provider_trade_no", models.CharField(blank=True, default="", max_length=64)),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(choices=[("pending", "待发起"), ("processing", "处理中"), ("succeeded", "成功"), ("failed", "失败")], default="pending", max_length=32),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.CharField(blank=True, default="", max_length=255)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawal_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payouts", to="wallet.withdrawalrequest")),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="withdrawalrequest",
            constraint=models.UniqueConstraint(fields=("user", "client_request_id"), name="wallet_withdraw_user_client_req_uniq"),
        ),
    ]
