# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_move_withdrawal_payout_to_payments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletaccount",
            name="available_balance",
            field=models.BigIntegerField(default=0, verbose_name="可用余额"),
        ),
        migrations.AlterField(
            model_name="walletaccount",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="walletaccount",
            name="frozen_balance",
            field=models.BigIntegerField(default=0, verbose_name="冻结余额"),
        ),
        migrations.AlterField(
            model_name="walletaccount",
            name="total_income",
            field=models.BigIntegerField(default=0, verbose_name="累计收入"),
        ),
        migrations.AlterField(
            model_name="walletaccount",
            name="total_withdrawn",
            field=models.BigIntegerField(default=0, verbose_name="累计提现"),
        ),
        migrations.AlterField(
            model_name="walletaccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="walletaccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_account",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="amount_delta",
            field=models.BigIntegerField(verbose_name="金额变动"),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="available_balance_after",
            field=models.BigIntegerField(verbose_name="变动后可用余额"),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="biz_id",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="业务标识"
            ),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="biz_type",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="业务类型"
            ),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="entry_type",
            field=models.CharField(max_length=64, verbose_name="流水类型"),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="frozen_balance_after",
            field=models.BigIntegerField(verbose_name="变动后冻结余额"),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="idempotency_key",
            field=models.CharField(max_length=120, unique=True, verbose_name="幂等键"),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="remark",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="备注"
            ),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="walletledger",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledgers",
                to="wallet.walletaccount",
                verbose_name="钱包账户",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="amount",
            field=models.BigIntegerField(verbose_name="金额"),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="client_request_id",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="客户端请求标识"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="fee_amount",
            field=models.BigIntegerField(default=0, verbose_name="手续费金额"),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="net_amount",
            field=models.BigIntegerField(verbose_name="实际到账金额"),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="pay_channel",
            field=models.CharField(
                choices=[("wechat", "微信提现")],
                default="wechat",
                max_length=32,
                verbose_name="付款渠道",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="payee_account_snapshot",
            field=models.JSONField(default=dict, verbose_name="收款账户快照"),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="reject_reason",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="拒绝原因"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_withdrawals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "待审核"),
                    ("cancelled", "已撤销"),
                    ("rejected", "已驳回"),
                    ("approved", "已通过待打款"),
                    ("paying", "打款中"),
                    ("paid", "已打款"),
                    ("failed", "打款失败"),
                ],
                default="pending_review",
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawal_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawal_requests",
                to="wallet.walletaccount",
                verbose_name="钱包账户",
            ),
        ),
    ]
