# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_walletaccount_available_balance_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="walletaccount",
            options={"verbose_name": "钱包账户", "verbose_name_plural": "钱包账户"},
        ),
        migrations.AlterModelOptions(
            name="walletledger",
            options={
                "ordering": ("-created_at", "-pk"),
                "verbose_name": "钱包流水",
                "verbose_name_plural": "钱包流水",
            },
        ),
        migrations.AlterModelOptions(
            name="withdrawalrequest",
            options={
                "ordering": ("-created_at", "-pk"),
                "verbose_name": "提现申请",
                "verbose_name_plural": "提现申请",
            },
        ),
    ]
