# Generated by Django 5.2.14 on 2026-07-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_use_base_model_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="team",
            name="business_hours",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="team",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="team",
            name="wechat",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
