# Generated by Django 5.2.14 on 2026-08-27 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0011_alter_organizationmember_unique_together_and_more"),
        ("teams", "0003_team_address_team_business_hours_team_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(fields=("organization", "name"), name="teams_org_name_unique"),
        ),
    ]
