# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_alter_organization_archived_at_and_more"),
        ("teams", "0004_alter_team_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="地址"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="business_hours",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="营业时间"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="团队成员",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100, verbose_name="团队名称"),
        ),
        migrations.AlterField(
            model_name="team",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="手机号"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="team",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="wechat",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="微信号"
            ),
        ),
    ]
