# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_alter_team_address_alter_team_business_hours_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "团队", "verbose_name_plural": "团队"},
        ),
    ]
