# Generated by Django 5.2.14 on 2026-07-18 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0008_organization_description_organization_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_name", models.CharField(max_length=96)),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.CharField(max_length=64)),
                ("source", models.CharField(max_length=32)),
                ("anonymous_id_hash", models.CharField(blank=True, max_length=64)),
                ("session_id_hash", models.CharField(blank=True, max_length=64)),
                ("visitor_key", models.CharField(blank=True, max_length=80)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("occurred_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytics_events", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analytics_events", to="organizations.organization")),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
                "indexes": [
                    models.Index(fields=["organization", "event_name", "occurred_at"], name="ana_org_event_time_idx"),
                    models.Index(fields=["organization", "target_type", "target_id", "occurred_at"], name="ana_org_target_time_idx"),
                    models.Index(fields=["organization", "source", "occurred_at"], name="ana_org_source_time_idx"),
                    models.Index(fields=["organization", "visitor_key", "occurred_at"], name="ana_org_visitor_time_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key", ""), _negated=True), fields=("organization", "source", "idempotency_key"), name="analytics_event_idempotency_uniq"
                    )
                ],
            },
        ),
    ]
