# Generated by Django 5.2.14 on 2026-07-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("organizations", "0008_organization_description_organization_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsDailyMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("source", models.CharField(blank=True, max_length=32)),
                ("scope", models.CharField(max_length=16)),
                ("event_name", models.CharField(blank=True, max_length=96)),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("event_count", models.PositiveBigIntegerField()),
                ("unique_visitors", models.PositiveBigIntegerField()),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analytics_daily_metrics", to="organizations.organization"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="analyticsdailymetric",
            constraint=models.UniqueConstraint(
                fields=("organization", "source", "scope", "date", "event_name", "target_type", "target_id"),
                name="analytics_daily_metric_uniq",
            ),
        ),
    ]
