# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_analyticsdailymetric"),
        ("organizations", "0012_alter_organization_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsdailymetric",
            name="date",
            field=models.DateField(verbose_name="日期"),
        ),
        migrations.AlterField(
            model_name="analyticsdailymetric",
            name="event_count",
            field=models.PositiveBigIntegerField(verbose_name="事件数量"),
        ),
        migrations.AlterField(
            model_name="analyticsdailymetric",
            name="event_name",
            field=models.CharField(blank=True, max_length=96, verbose_name="事件名称"),
        ),
        migrations.AlterField(
            model_name="analyticsdailymetric",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_daily_metrics",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsdailymetric",
            name="scope",
            field=models.CharField(max_length=16, verbose_name="作用域"),
        ),
        migrations.AlterField(
            model_name="analyticsdailymetric",
            name="source",
            field=models.CharField(blank=True, max_length=32, verbose_name="来源"),
        ),
        migrations.AlterField(
            model_name="analyticsdailymetric",
            name="target_id",
            field=models.CharField(blank=True, max_length=64, verbose_name="目标标识"),
        ),
        migrations.AlterField(
            model_name="analyticsdailymetric",
            name="target_type",
            field=models.CharField(blank=True, max_length=64, verbose_name="目标类型"),
        ),
        migrations.AlterField(
            model_name="analyticsdailymetric",
            name="unique_visitors",
            field=models.PositiveBigIntegerField(verbose_name="独立访客数"),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="anonymous_id_hash",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="匿名用户标识哈希"
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_name",
            field=models.CharField(max_length=96, verbose_name="事件名称"),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=128, verbose_name="幂等键"),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="occurred_at",
            field=models.DateTimeField(verbose_name="发生时间"),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_events",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="properties",
            field=models.JSONField(blank=True, default=dict, verbose_name="事件属性"),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="received_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="接收时间"),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="session_id_hash",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="会话标识哈希"
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="source",
            field=models.CharField(max_length=32, verbose_name="来源"),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="target_id",
            field=models.CharField(max_length=64, verbose_name="目标标识"),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="target_type",
            field=models.CharField(max_length=64, verbose_name="目标类型"),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="visitor_key",
            field=models.CharField(blank=True, max_length=80, verbose_name="访客标识"),
        ),
    ]
