# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alter_analyticsdailymetric_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyticsdailymetric",
            options={
                "verbose_name": "每日分析指标",
                "verbose_name_plural": "每日分析指标",
            },
        ),
        migrations.AlterModelOptions(
            name="analyticsevent",
            options={
                "ordering": ("-occurred_at", "-id"),
                "verbose_name": "分析事件",
                "verbose_name_plural": "分析事件",
            },
        ),
    ]
