# Generated by Codex on 2026-05-29

from django.db import migrations

# Frozen historical baseline for fresh databases migrating through this point.
# Runtime synchronization now happens from `apps.access.constants` and `apps.access.sync`.
HISTORICAL_PERMISSIONS = {
    "access": [
        ("role_view", "查看访问角色"),
        ("role_manage", "管理访问角色"),
        ("team_role_view", "查看团队访问角色绑定"),
        ("team_role_manage", "管理团队访问角色绑定"),
    ],
    "organizations": [
        ("member_view", "查看组织成员"),
        ("member_manage", "管理组织成员"),
        ("invite_manage", "管理组织邀请"),
        ("setting_manage", "管理组织设置"),
    ],
    "teams": [
        ("team_view", "查看团队"),
        ("team_create", "创建团队"),
        ("team_update", "更新团队"),
        ("team_delete", "删除团队"),
        ("team_member_manage", "管理团队成员"),
    ],
    "settings": [
        ("org_setting_view", "查看组织设置"),
        ("org_setting_manage", "管理组织设置"),
        ("team_setting_view", "查看团队设置"),
        ("team_setting_manage", "管理团队设置"),
    ],
}

HISTORICAL_ROLES = {
    "org_admin": {
        "scope": "org",
        "name": "Organization admin",
        "permissions": [
            "access.role_view",
            "access.role_manage",
            "access.team_role_view",
            "access.team_role_manage",
            "organizations.member_view",
            "organizations.member_manage",
            "organizations.invite_manage",
            "organizations.setting_manage",
            "teams.team_view",
            "teams.team_create",
            "teams.team_update",
            "teams.team_delete",
            "teams.team_member_manage",
            "settings.org_setting_view",
            "settings.org_setting_manage",
            "settings.team_setting_view",
            "settings.team_setting_manage",
        ],
    },
    "org_finance": {
        "scope": "org",
        "name": "Organization finance",
        "permissions": [],
    },
    "team_manager": {
        "scope": "team",
        "name": "Team manager",
        "permissions": [
            "teams.team_view",
            "teams.team_update",
            "teams.team_member_manage",
            "settings.team_setting_view",
            "settings.team_setting_manage",
        ],
    },
    "team_finance": {
        "scope": "team",
        "name": "Team finance",
        "permissions": [],
    },
    "team_staff": {
        "scope": "team",
        "name": "Team staff",
        "permissions": ["teams.team_view", "settings.team_setting_view"],
    },
    "team_viewer": {
        "scope": "team",
        "name": "Team viewer",
        "permissions": ["teams.team_view", "settings.team_setting_view"],
    },
}


def seed_roles(apps, schema_editor):
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")
    access_role_model = apps.get_model("access", "AccessRole")

    permissions_by_key = {}
    for app_label, permissions in HISTORICAL_PERMISSIONS.items():
        content_type, _ = content_type_model.objects.get_or_create(app_label=app_label, model="accesspermission")
        for codename, name in permissions:
            permission, _ = permission_model.objects.get_or_create(
                content_type=content_type,
                codename=codename,
                defaults={"name": name},
            )
            permissions_by_key[f"{app_label}.{codename}"] = permission

    for code, role_data in HISTORICAL_ROLES.items():
        group, _ = group_model.objects.get_or_create(name=code)
        group.permissions.set([permissions_by_key[key] for key in role_data["permissions"]])
        access_role_model.objects.update_or_create(
            group=group,
            defaults={
                "organization": None,
                "scope": role_data["scope"],
                "code": code,
                "name": role_data["name"],
                "is_system": True,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(seed_roles, migrations.RunPython.noop),
    ]
