# Generated by Codex on 2026-05-29

from django.db import migrations

PERMISSIONS = {
    "access": [
        ("role_view", "Can view access roles"),
        ("role_manage", "Can manage access roles"),
        ("team_role_view", "Can view team access role bindings"),
        ("team_role_manage", "Can manage team access role bindings"),
    ],
    "organizations": [
        ("member_view", "Can view organization members"),
        ("member_manage", "Can manage organization members"),
        ("invite_manage", "Can manage organization invites"),
        ("setting_manage", "Can manage organization settings"),
    ],
    "teams": [
        ("team_view", "Can view teams"),
        ("team_create", "Can create teams"),
        ("team_update", "Can update teams"),
        ("team_delete", "Can delete teams"),
        ("team_member_manage", "Can manage team members"),
    ],
    "settings": [
        ("org_setting_view", "Can view organization settings"),
        ("org_setting_manage", "Can manage organization settings"),
        ("team_setting_view", "Can view team settings"),
        ("team_setting_manage", "Can manage team settings"),
    ],
}

ROLES = {
    "org_admin": {
        "scope": "org",
        "name": "Organization admin",
        "permissions": [
            "access.role_view",
            "access.role_manage",
            "access.team_role_view",
            "access.team_role_manage",
            "organizations.member_view",
            "organizations.member_manage",
            "organizations.invite_manage",
            "organizations.setting_manage",
            "teams.team_view",
            "teams.team_create",
            "teams.team_update",
            "teams.team_delete",
            "teams.team_member_manage",
            "settings.org_setting_view",
            "settings.org_setting_manage",
            "settings.team_setting_view",
            "settings.team_setting_manage",
        ],
    },
    "org_finance": {
        "scope": "org",
        "name": "Organization finance",
        "permissions": [],
    },
    "team_manager": {
        "scope": "team",
        "name": "Team manager",
        "permissions": [
            "teams.team_view",
            "teams.team_update",
            "teams.team_member_manage",
            "settings.team_setting_view",
            "settings.team_setting_manage",
        ],
    },
    "team_finance": {
        "scope": "team",
        "name": "Team finance",
        "permissions": [],
    },
    "team_staff": {
        "scope": "team",
        "name": "Team staff",
        "permissions": ["teams.team_view", "settings.team_setting_view"],
    },
    "team_viewer": {
        "scope": "team",
        "name": "Team viewer",
        "permissions": ["teams.team_view", "settings.team_setting_view"],
    },
}


def seed_roles(apps, schema_editor):
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")
    access_role_model = apps.get_model("access", "AccessRole")

    permissions_by_key = {}
    for app_label, permissions in PERMISSIONS.items():
        content_type, _ = content_type_model.objects.get_or_create(app_label=app_label, model="accesspermission")
        for codename, name in permissions:
            permission, _ = permission_model.objects.get_or_create(
                content_type=content_type,
                codename=codename,
                defaults={"name": name},
            )
            permissions_by_key[f"{app_label}.{codename}"] = permission

    for code, role_data in ROLES.items():
        group, _ = group_model.objects.get_or_create(name=code)
        group.permissions.set([permissions_by_key[key] for key in role_data["permissions"]])
        access_role_model.objects.update_or_create(
            group=group,
            defaults={
                "organization": None,
                "scope": role_data["scope"],
                "code": code,
                "name": role_data["name"],
                "is_system": True,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(seed_roles, migrations.RunPython.noop),
    ]
