# Generated by Codex on 2026-05-29

from django.db import migrations

# Frozen historical baseline for fresh databases migrating through this point.
# Runtime synchronization now happens from `apps.access.constants` and `apps.access.sync`.
HISTORICAL_FINANCE_PERMISSIONS = [
    ("finance_bill_view", "查看账单"),
    ("finance_bill_refund", "退款账单"),
    ("finance_report_export", "导出财务报表"),
]

HISTORICAL_ROLE_PERMISSIONS = {
    "org_admin": [
        "finance.finance_bill_view",
        "finance.finance_bill_refund",
        "finance.finance_report_export",
    ],
    "org_finance": [
        "finance.finance_bill_view",
        "finance.finance_bill_refund",
        "finance.finance_report_export",
    ],
    "team_finance": [
        "finance.finance_bill_view",
        "finance.finance_bill_refund",
    ],
}


def seed_finance_permissions(apps, schema_editor):
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")

    content_type, _ = content_type_model.objects.get_or_create(app_label="finance", model="accesspermission")
    permissions_by_key = {}
    for codename, name in HISTORICAL_FINANCE_PERMISSIONS:
        permission, _ = permission_model.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permissions_by_key[f"finance.{codename}"] = permission

    for code, permission_keys in HISTORICAL_ROLE_PERMISSIONS.items():
        group = group_model.objects.filter(name=code).first()
        if group is None:
            continue
        group.permissions.add(*[permissions_by_key[key] for key in permission_keys])


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0002_seed_system_roles"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(seed_finance_permissions, migrations.RunPython.noop),
    ]
