# Generated by Codex on 2026-05-30

from django.db import migrations

PERMISSION_NAMES = {
    "access": {
        "role_view": "查看访问角色",
        "role_manage": "管理访问角色",
        "team_role_view": "查看团队访问角色绑定",
        "team_role_manage": "管理团队访问角色绑定",
    },
    "organizations": {
        "member_view": "查看组织成员",
        "member_manage": "管理组织成员",
        "invite_manage": "管理组织邀请",
        "setting_manage": "管理组织设置",
    },
    "teams": {
        "team_view": "查看团队",
        "team_create": "创建团队",
        "team_update": "更新团队",
        "team_delete": "删除团队",
        "team_member_manage": "管理团队成员",
    },
    "settings": {
        "org_setting_view": "查看组织设置",
        "org_setting_manage": "管理组织设置",
        "team_setting_view": "查看团队设置",
        "team_setting_manage": "管理团队设置",
    },
    "finance": {
        "finance_bill_view": "查看账单",
        "finance_bill_refund": "退款账单",
        "finance_report_export": "导出财务报表",
    },
}


def update_permission_names(apps, schema_editor):
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")

    for app_label, names_by_codename in PERMISSION_NAMES.items():
        content_type = content_type_model.objects.filter(app_label=app_label, model="accesspermission").first()
        if content_type is None:
            continue
        for codename, name in names_by_codename.items():
            permission_model.objects.filter(content_type=content_type, codename=codename).update(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0003_seed_finance_permissions"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(update_permission_names, migrations.RunPython.noop),
    ]
