# Generated by Django 5.2.14 on 2026-08-27 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0006_role_description_and_team_scope"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0011_alter_organizationmember_unique_together_and_more"),
        ("teams", "0004_alter_team_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationgroupbinding",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="teamgroupbinding",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="organizationgroupbinding",
            constraint=models.UniqueConstraint(fields=("organization", "user", "group"), name="access_org_user_group_unique"),
        ),
        migrations.AddConstraint(
            model_name="teamgroupbinding",
            constraint=models.UniqueConstraint(fields=("team", "user", "group"), name="access_team_user_group_unique"),
        ),
    ]
