# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0007_alter_organizationgroupbinding_unique_together_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0011_alter_organizationmember_unique_together_and_more"),
        ("teams", "0004_alter_team_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrole",
            name="code",
            field=models.SlugField(max_length=80, verbose_name="编码"),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_role",
                to="auth.group",
                verbose_name="权限组",
            ),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="is_system",
            field=models.BooleanField(default=False, verbose_name="是否系统内置"),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="name",
            field=models.CharField(max_length=80, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_roles",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="scope",
            field=models.CharField(
                choices=[("org", "Org"), ("team", "Team")],
                max_length=20,
                verbose_name="作用域",
            ),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_roles",
                to="teams.team",
                verbose_name="团队",
            ),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="organizationgroupbinding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="organizationgroupbinding",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="organizationgroupbinding",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
                verbose_name="权限组",
            ),
        ),
        migrations.AlterField(
            model_name="organizationgroupbinding",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="organizationgroupbinding",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="organizationgroupbinding",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="organizationgroupbinding",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="teamgroupbinding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="teamgroupbinding",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="teamgroupbinding",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
                verbose_name="权限组",
            ),
        ),
        migrations.AlterField(
            model_name="teamgroupbinding",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
                verbose_name="团队",
            ),
        ),
        migrations.AlterField(
            model_name="teamgroupbinding",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="teamgroupbinding",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="teamgroupbinding",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
