# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0008_alter_accessrole_code_alter_accessrole_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessrole",
            options={"verbose_name": "访问角色", "verbose_name_plural": "访问角色"},
        ),
        migrations.AlterModelOptions(
            name="organizationgroupbinding",
            options={
                "verbose_name": "组织用户组绑定",
                "verbose_name_plural": "组织用户组绑定",
            },
        ),
        migrations.AlterModelOptions(
            name="teamgroupbinding",
            options={
                "verbose_name": "团队用户组绑定",
                "verbose_name_plural": "团队用户组绑定",
            },
        ),
    ]
