# Generated by Django 5.2.14 on 2026-06-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_use_base_model_timestamps'),
        ('organizations', '0006_organization_lifecycle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvite',
            name='access_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.accessrole'),
        ),
    ]
