# Generated by Django 5.2.14 on 2026-07-18 16:11

from django.db import migrations, models

import apps.media.fields


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_organizationinvite_access_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=apps.media.fields.MediaRefsField(
                allowed_media_types=["image"],
                allowed_resource_types=["org_logo"],
                blank=True,
                business_validators=["apps.organizations.services.validate_organization_media_refs"],
                default=list,
                max_items=1,
                verbose_name="logo",
            ),
        ),
    ]
