# Generated by Django 5.2.14 on 2026-07-24 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_organization_description_organization_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # BaseModelMixin 过去已占用 created_by 字符列作为审计值。订阅域需要
            # 不可变的创建人外键，但不能把旧字符串强制转换为用户 id；存量组织
            # 应保持 NULL，因此保留旧列并新增 created_by_id。
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE organizations_organization ADD COLUMN created_by_id bigint NULL; "
                        "ALTER TABLE organizations_organization ADD CONSTRAINT organizations_org_created_by_fk "
                        "FOREIGN KEY (created_by_id) REFERENCES accounts_user(id) ON DELETE SET NULL; "
                        "CREATE INDEX organizations_org_created_by_idx ON organizations_organization(created_by_id);"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="organization",
                    name="created_by",
                    field=models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_organizations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
