# Generated by Django 5.2.12 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0009_alter_organization_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinvite",
            name="invitee_phone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
