# Generated by Django 5.2.14 on 2026-08-27 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_organizationinvite_invitee_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationmember",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                error_messages={
                    "invalid": "请输入仅包含字母、数字、下划线或连字符的有效标识。",
                    "unique": "该组织标识已被占用。",
                },
                help_text="The account name is like a username and ideally should be lower case and short.",
                max_length=40,
                unique=True,
                verbose_name="account name",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmember",
            constraint=models.UniqueConstraint(
                fields=("organization", "user"),
                name="organizations_org_user_unique",
                violation_error_message="该用户已是此组织成员。",
            ),
        ),
    ]
