# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0008_alter_accessrole_code_alter_accessrole_created_at_and_more"),
        ("organizations", "0011_alter_organizationmember_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="归档时间"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="billing_email",
            field=models.EmailField(
                blank=True,
                help_text="The email address that receipts are sent.",
                max_length=254,
                null=True,
                verbose_name="账单邮箱",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_organizations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="member_limit",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="成员数量上限"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="team_limit",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="团队数量上限"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="access_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="access.accessrole",
                verbose_name="访问角色",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="invitee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="受邀人",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="invitee_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="受邀人邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="invitee_phone",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="受邀人手机号"
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="key",
            field=models.CharField(editable=False, max_length=32, verbose_name="键"),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="邀请人",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
