# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_alter_organization_archived_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"verbose_name": "组织", "verbose_name_plural": "组织"},
        ),
        migrations.AlterModelOptions(
            name="organizationinvite",
            options={"verbose_name": "组织邀请", "verbose_name_plural": "组织邀请"},
        ),
        migrations.AlterModelOptions(
            name="organizationmember",
            options={"verbose_name": "组织成员", "verbose_name_plural": "组织成员"},
        ),
    ]
