# Generated by Django 5.2.14 on 2026-08-29 07:11

import apps.media.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="组织描述"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=apps.media.fields.MediaRefsField(
                allowed_media_types=["image"],
                allowed_resource_types=["org_logo"],
                blank=True,
                business_validators=[
                    "apps.organizations.services.validate_organization_media_refs"
                ],
                default=list,
                max_items=1,
                verbose_name="组织标志",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                error_messages={
                    "invalid": "请输入仅包含字母、数字、下划线或连字符的有效标识。",
                    "unique": "该组织标识已被占用。",
                },
                help_text="The account name is like a username and ideally should be lower case and short.",
                max_length=40,
                unique=True,
                verbose_name="组织标识",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="is_owner",
            field=models.BooleanField(default=False, verbose_name="是否所有者"),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="is_owner",
            field=models.BooleanField(default=False, verbose_name="是否所有者"),
        ),
    ]
