# Generated by Django 5.2.14 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0014_alter_organization_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="employee_name",
            field=models.CharField(blank=True, default="", max_length=150, verbose_name="员工姓名"),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="职位"),
        ),
    ]
