# Generated by Django 5.2.14 on 2026-06-03 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_use_base_model_timestamps'),
        ('organizations', '0005_use_base_model_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_6e705f_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_61125d_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'organization', '-created_at'], name='notificatio_recipie_6e705f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'category', '-created_at'], name='notificatio_recipie_61125d_idx'),
        ),
    ]
