# Generated by Django 5.2.14 on 2026-06-19 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_notificatio_recipie_6e705f_idx_and_more'),
        ('organizations', '0006_organization_lifecycle_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('organization', 'Organization'), ('users', 'Users')], max_length=32)),
                ('scope_ids', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('owner_organization', models.ForeignKey(blank=True, help_text='Management owner; null means platform-owned.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatches', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='dispatch',
            field=models.ForeignKey(blank=True, help_text='The management dispatch that produced this inbox row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationdispatch'),
        ),
        migrations.AddIndex(
            model_name='notificationdispatch',
            index=models.Index(fields=['owner_organization', '-created_at'], name='notif_dispatch_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdispatch',
            index=models.Index(fields=['scope', '-created_at'], name='notif_dispatch_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdispatch',
            index=models.Index(fields=['status', '-created_at'], name='notif_dispatch_status_idx'),
        ),
    ]
