# Generated by Django 5.2.14 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_notification_dispatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationdispatch",
            name="scope",
            field=models.CharField(
                choices=[
                    ("platform", "Platform"),
                    ("organization", "Organization"),
                    ("teams", "Teams"),
                    ("users", "Users"),
                ],
                max_length=32,
            ),
        ),
    ]
