# Generated by Django 5.2.14 on 2026-08-27 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_alter_notificationdispatch_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(fields=("user", "category"), name="notifications_user_cat_unique"),
        ),
    ]
