# Generated by Django 5.2.14 on 2026-08-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notifications", "0006_alter_notificationpreference_unique_together_and_more"),
        ("organizations", "0012_alter_organization_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                help_text="The user whose action produced this notification (null for system events).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="body",
            field=models.TextField(blank=True, verbose_name="正文"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Producer-defined category key — see apps/notifications/categories.py.",
                max_length=64,
                verbose_name="分类",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="data",
            field=models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="dispatch",
            field=models.ForeignKey(
                blank=True,
                help_text="The management dispatch that produced this inbox row.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="notifications.notificationdispatch",
                verbose_name="通知任务",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Per-row retention override; cleanup deletes the row once this time has passed.",
                null=True,
                verbose_name="过期时间",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Org scope; null for personal/global notifications.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="阅读时间"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                help_text="The user who will see this notification in their inbox.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收人",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="目标内容类型",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_object_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="目标对象标识"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="链接地址"
            ),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="body",
            field=models.TextField(blank=True, verbose_name="正文"),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="category",
            field=models.CharField(blank=True, max_length=64, verbose_name="分类"),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="created_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="data",
            field=models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="delivered_count",
            field=models.PositiveIntegerField(default=0, verbose_name="送达数量"),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="错误信息"),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="owner_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Management owner; null means platform-owned.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_dispatches",
                to="organizations.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="scope",
            field=models.CharField(
                choices=[
                    ("platform", "Platform"),
                    ("organization", "Organization"),
                    ("teams", "Teams"),
                    ("users", "Users"),
                ],
                max_length=32,
                verbose_name="作用域",
            ),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="scope_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="作用域标识列表"
            ),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发送时间"),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="target_count",
            field=models.PositiveIntegerField(default=0, verbose_name="目标数量"),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="title",
            field=models.CharField(max_length=255, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="updated_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="链接地址"
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="category",
            field=models.CharField(max_length=64, verbose_name="分类"),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="email",
            field=models.BooleanField(default=False, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="in_app",
            field=models.BooleanField(default=True, verbose_name="站内通知"),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
