# Generated by Django 5.2.14 on 2026-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0007_alter_notification_actor_alter_notification_body_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationdispatch",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "通知派发任务",
                "verbose_name_plural": "通知派发任务",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationpreference",
            options={"verbose_name": "通知偏好", "verbose_name_plural": "通知偏好"},
        ),
    ]
